### ISSUE TITLE
Where can i see data related to recordScreenView ?

### ISSUE THREAD

**Issue by rajaishwary** [CleverTap/clevertap-react-native#10]
following part of code.

```
RCT_EXPORT_METHOD(recordScreenView:(NSString*)screenName) {
    RCTLogInfo(@"[CleverTap recordScreenView]");
    [[CleverTap sharedInstance] recordScreenView:screenName];
}
```
used is js as:
```CleverTap.recordScreenView(screenName);```

**Comment by rajaishwary** [comment]
following part of code.
```
RCT_EXPORT_METHOD(recordScreenView:(NSString*)screenName) {
    RCTLogInfo(@"[CleverTap recordScreenView]");
    [[CleverTap sharedInstance] recordScreenView:screenName];
}
```

used is js as: 
```CleverTap.recordScreenView(screenName);```

**Comment by pwilkniss** [comment]
@rajaishwary  that needs to be enabled on your CleverTap account/dashboard.  Please email support at clevertap dotcom with your account info and query.  That will be the best channel for you to get this resolved.
