### ISSUE TITLE
removeListeners function kills all listners in app

### ISSUE THREAD

**Issue by HasanSahabGlobal** [CleverTap/clevertap-react-native#104]
all listeners in app such as react-navigation listener to detect "swipeToBack" event on Android, and so on, killed by removeListeners function.

expected: another function to remove event by name, not all

**Comment by AbdullhRtima** [comment]
up

**Comment by piyush-kukadiya** [comment]
@HasanSahabGlobal @AbdullhRtima 
If it's removing all non-clevertap listeners then I would suggest not to use that method. You can manually remove clevertap listeners at your end. We would be changing the logic for this method in next release.
Thanks

**Comment by HasanSahabGlobal** [comment]
@piyush-kukadiya 
how i can remove them manually?
you are not using the EventEmiiter from react-native, you have your own.

`const EventEmitter = NativeModules.CleverTapReactEventEmitter ? new NativeEventEmitter(NativeModules.CleverTapReactEventEmitter) : DeviceEventEmitter;`

check this line in index.js

**Comment by piyush-kukadiya** [comment]
Oops! my bad, I missed that.
 @HasanSahabGlobal As of now the only solution that I can see here is avoiding calling `removeListeners`   We will be changing logic for the same in next release and probably adding an extra method to remove single listener

**Comment by HasanSahabGlobal** [comment]
@piyush-kukadiya 
thank you very much for fast response.
