### ISSUE TITLE
Build fails in Android for both debug and release

### ISSUE THREAD

**Issue by Arun-paramasivam** [CleverTap/clevertap-react-native#109]
It was working fine till yesterday. Haven't changed any code related to clever tap or added any new packages.
I get this error today. But works fine on iOS.

When run on a Device the following error occurs:
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/user/application/MobileApp/app/android/app/src/main/java/com/app/MainActivity.java:18: error: cannot access CTPushNotificationListener
    CleverTapModule.setInitialUri(getIntent().getData());
                   ^
  class file for com.clevertap.android.sdk.CTPushNotificationListener not found
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by piyush-kukadiya** [comment]
@Arun-paramasivam Which SDK version are you using?

**Comment by Arun-paramasivam** [comment]
Hi @piyush-kukadiya ,

My podfile.lock has the following version,
  - clevertap-react-native (0.4.5):
    - CleverTap-iOS-SDK (~> 3.8.2)
    - React
  - CTNotificationService (0.1.2)

**Comment by d11-dinesh** [comment]
Getting the same error.

**Comment by SauravKale** [comment]
Hi @piyush-kukadiya and @d11-dinesh ,

Could you confirm if you have added the Push Notification Callback code give in the following documents https://developer.clevertap.com/docs/android#section-push-notification-callback
https://developer.clevertap.com/docs/android#section-push-notifications

**Comment by d11-dinesh** [comment]
MainActivity cannot be converted to CTPushNotificationListener

**Comment by piyush-kukadiya** [comment]
@Arun-paramasivam and @d11-dinesh, ` class file for com.clevertap.android.sdk.CTPushNotificationListener not found ` seems like compiler is unable to find the class. However`com.clevertap.android:clevertap-android-sdk:3.8.2` is having `CTPushNotificationListener` defined in `com.clevertap.android.sdk` package. It's also working from my end. I would suggest you to check if this dependency is properly resolved in your project.

**Comment by Arun-paramasivam** [comment]
Hi @piyush-kukadiya ,

Adding the following receiver to the Androidmanifest file did the work,

`<receiver
            android:name="com.clevertap.android.sdk.CTPushNotificationReceiver"
            android:enabled="true"
            android:exported="false" />`

it was working fine till last week, but not sure why the previous builds were successful. It was not mentioned in the clevertap-react-native docs. But found this on the example project. So its working for me now.

**Comment by piyush-kukadiya** [comment]
Hey @Arun-paramasivam, Adding  `<receiver android:name="com.clevertap.android.sdk.CTPushNotificationReceiver" android:enabled="true" android:exported="false" />` in manifest and `class file for com.clevertap.android.sdk.CTPushNotificationListener not found` has no connection between them, `CTPushNotificationListener` is just a callback in JAVA. 

Also Sorry for documentation part, we are working on smooth documentation to ease integration process.

**Comment by Arun-paramasivam** [comment]
Hi @piyush-kukadiya ,

yeah, even I was wondering what was causing the error and how it got resolved. But adding those manifest file lines did the trick.

Thanks for the quick response, closing the issue since its resolved.

**Comment by mouryaavadhesh** [comment]
> @Arun-paramasivam and @d11-dinesh, `class file for com.clevertap.android.sdk.CTPushNotificationListener not found` seems like compiler is unable to find the class. However`com.clevertap.android:clevertap-android-sdk:3.8.2` is having `CTPushNotificationListener` defined in `com.clevertap.android.sdk` package. It's also working from my end. I would suggest you to check if this dependency is properly resolved in your project.

This is not working for me. Still getting the error

**Comment by CHANDRAMOHANnegi** [comment]
Solved issue by updating     "clevertap-react-native": "^0.5.0"
