### ISSUE TITLE
[Android] Expose CleverTapModule.getCleverTapAPI for integrations with other platforms

### ISSUE THREAD

**Issue by shivawu** [CleverTap/clevertap-react-native#11]
I'm trying to integrate with branch.io, where according to their docs, one has to call `getCleverTapAttributionIdentifier` on the CleverTapAPI instance, but the API initiailized in CleverTapModule is private, so I have to create another API using `CleverTapAPI.getInstance` with potentially different context and internally it's still a singleton, so weird things might happen.

https://docs.branch.io/pages/integrations/clevertap/#android

**Comment by darshanclevertap** [comment]
Hi @shivawu 

You can use the JS method for it as explained in the ExampleProject.js file of the Example Project like this -

```
CleverTap.profileGetCleverTapAttributionIdentifier((err, res) => {
            console.log('CleverTapAttributionIdentifier', res, err);
        });
```

**Comment by shivawu** [comment]
Thanks for getting back at me, I'm not sure if that would work because the integration guide asks to put the method call in onCreate of the activity?
