### ISSUE TITLE
Clear notifications

### ISSUE THREAD

**Issue by BMariscal** [CleverTap/clevertap-react-native#110]
Hello!
Which method should I call to clear notifications?
 https://github.com/CleverTap/clevertap-react-native/blob/master/Starter/App.js

Note, I don't want to unsubscribe from notifications, just clear them. Thanks!

**Comment by piyush-kukadiya** [comment]
Hey @BMariscal ,
Can you please explain your use case in detail that what are you trying to achieve?

**Comment by Aditi3** [comment]
Closing it due to inactivity, feel free to reopen if you need further help.
