### ISSUE TITLE
Push notification for iOS app is not working on latest react native v0.63.3

### ISSUE THREAD

**Issue by rajeshsoni-eezi** [CleverTap/clevertap-react-native#116]
I tried the starter application provided by CT. I am able to get push notification token using starter app.
the starter application is based on 0.62.2
My application is using the latest react native version 0.63.3. 

In this latest version, the pod file structure was revised. Using my application code I am not able to get a push token.

This is my pod file:

```
target 'CTPushNotification' do
  config = use_native_modules!
  # use_frameworks!
  use_react_native!(:path => config["reactNativePath"])
  # pod 'CleverTap-iOS-SDK'
  pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native'
  target 'CTPushNotificationTests' do
    inherit! :complete
    # Pods for testing
  end
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'CTPushNotification-tvOS' do
  # Pods for CTPushNotification-tvOS

  target 'CTPushNotification-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

when we use use_frameworks! it shows below error:

"...target has transitive dependencies that include statically linked binaries."

I have latest version of cocoapod.

Please suggest

**Comment by Aditi3** [comment]
Hi @rajeshsoni-eezi 

We have updated our [Starter Application](https://github.com/CleverTap/clevertap-react-native/tree/master/Starter) to the lastest version of React native v0.63.3 and based on our testing, Push Notifications and Integration seems to be working correctly. 

Could you verify integration once at your end by seeing updated Starter Application?

Also, ensure to use the `registerForPush` [API](https://github.com/CleverTap/clevertap-react-native/blob/master/index.js#L100) to register and fetch the APNS token.

Our Starter Application link describing APNS implementation: https://github.com/CleverTap/clevertap-react-native/blob/master/Starter/App.js#L66

Hope this helps.

**Comment by rajeshsoni-eezi** [comment]
Thanks.. working now.

**Comment by Aditi3** [comment]
Glad it worked for you. Closing this.
