### ISSUE TITLE
Read notification data

### ISSUE THREAD

**Issue by aamir-ans** [CleverTap/clevertap-react-native#118]
Data receiving on firebase messaging method looks like this 
`{
  "data": {
    "nm": "Notification test",
    "nt": "Test",
    "wzrk_acct_id": "TEST-###-###-###",
    "wzrk_bc": "",
    "wzrk_bi": "2",
    "wzrk_cid": "",
    "wzrk_dt": "FIREBASE",
    "wzrk_id": "0_0",
    "wzrk_pivot": "wzrk_default",
    "wzrk_pn": "true",
    "wzrk_push_amp": "false",
    "wzrk_rnv": "false",
    "wzrk_ttl": "1604495979"
  },
  "from": "618955247303",
  "messageId": "0:1604409582030477%6ed5e001f9fd7ecd",
  "sentTime": 1604409582026,
  "ttl": 86400
}`

How can I get exact notification data like title, sub title etc received from cleverTap. @Aditi3

**Comment by piyush-kukadiya** [comment]
@aamir-ans I am not getting your question. I am assuming that you are looking for title, message etc. in payload
`nt` stands for `Notification Title`
`nm` stands for `Notification Body` For more info [go to step 3](https://developer.clevertap.com/docs/android#section-custom-android-push-notifications-handling)

And if you are asking for readymade methods for title, body etc. then that you will have to extract manually [using custom handling PN](https://developer.clevertap.com/docs/android#section-custom-android-push-notifications-handling)

**Comment by Aditi3** [comment]
Closing it, feel free to reopen if you need further help.
