### ISSUE TITLE
How to close AppInbox When tap

### ISSUE THREAD

**Issue by kanapan** [CleverTap/clevertap-react-native#120]
How to close AppInbox When tap deep link in messages

**Comment by piyush-kukadiya** [comment]
@kanapan Why do you want to do that. For a better User experience, user must land to the same place where he had been taken off.

**Comment by kanapan** [comment]
Because we want to navigate in the app, but AppInbox obstructs the rear view

**Comment by piyush-kukadiya** [comment]
@kanapan Sorry but we don't have any public api for your use case. However we can consider it for future releases.

**Comment by CHANDRAMOHANnegi** [comment]
How to close notification when user click on Action button

I have a action button "Add to cart"  when user click on that , notification is not getting closed , user redirects to app.
i want to remove that notification from notification tray , after click
