### ISSUE TITLE
Xioami push service causing crahes

### ISSUE THREAD

**Issue by LonelyCpp** [CleverTap/clevertap-react-native#124]
We recently integrated xiaomi's push notifications through clevertap with

`com.clevertap.android:clevertap-xiaomi-sdk:1.0.0`

We started noticing random crashes from this pushservice - 

```
FATAL EXCEPTION: main
Process: com.app.android:pushservice, PID: 18726
java.lang.RuntimeException: Unable to create application com.app.android.MainApplication: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5925)
	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
...
```

extra details:
- app is in react native. (clevertap-react-native: `v0.5.0`)
- android specific crash
- seems to happen mainly on Android 9 devices
- happens right at launch, but continues to work after clicking "restart app"
- 100% reproducible on fresh launches
- 100% goes away if `clevertap-xiaomi-sdk` is removed as a dependency

**Comment by LonelyCpp** [comment]
Hi, I tried it on a fresh project (the starter is hard to setup because of the incompatible firebase config). It doesn't crash in this case. 

Any clue as to what might be wrong? (from the stack trace)

**Comment by piyush-kukadiya** [comment]
@LonelyCpp This mainly occurs when same `webview` instance is used for multiple process [check here](https://arjun30.medium.com/webview-data-directory-for-android-9-pie-d9744a1404e9).
Xiaomi hosts a service for push which runs in a different process however, Xiaomi sdk doesn’t use any webview internally.

There may be two possibilities:

1. React-native might be using webview for multiple process internally, in which case you can report a bug on react-native. Also there is already one open issue for the same [crash here](https://github.com/react-native-webview/react-native-webview/issues/968)

2. Report a bug through your xiaomi developer account to further investigate.

Also try to check how many processes are running for your app apart from xiaomi push(`your_package_name:pushservice[processId]`) and if keeping only one process alive fixes a bug then that has to be react-native issue.

**Comment by LonelyCpp** [comment]
The issue was caused by a webview related call in MainActivity `onCreate`.

This could potentially also cause a crash if xiaomi uses a webview in their notification service **while** the app is using a webview. (we weren't able to test this)

The solution:
Delay any calls related to `android.webkit.WebView`. Any references to this class during app launch will cause the app to crash on launch. (maybe this can be added as a note in the xiaomi integration docs)
