### ISSUE TITLE
Custom Key/Value pairs not being received

### ISSUE THREAD

**Issue by gusparis** [CleverTap/clevertap-react-native#127]
@Aditi3 On the Mobile In-App messages, when sending a custom key/value pair, the `kv` field is not present on the JSON received by the SDK. I don't know if is an issue with the RN port, or with the SDK itself. Attaching xcode debugger image, with the `kv` type, but no field.

![image](https://user-images.githubusercontent.com/17435926/103417379-410dba00-4b69-11eb-92dd-8c6ea1cecb4a.png)

Edit: 
The URL feature is working as expected.
clevertap-react-native: 0.5.0
CleverTap-iOS-SDK: 3.9.1

Edit 2:
This is happening while using the `Send Test` feature from the Campaign creation dashboard. The JSON is OK on the browser's request, but the field is cut off on the client-side.

JSON sent
> {"title":"CleverTap","message":"Touch this notification to open your app and view your in-app notification","gcmIds":"","apnsTokens":"C9F283FCAEB0539C2CFB6E8CA296AACEB4BC92CD8D4DD90E25AD3FE6F604BD37","type":"token","uids":[],"winUris":"","chromeIds":"","firefoxIds":"","safariIds":"","kv":{"1":{"wzrk_inapp":"{\"type\":\"cover\",\"bg\":\"#ffffff\",\"tablet\":false,\"close\":true,\"message\":{\"text\":\"Message\",\"color\":\"#434761\",\"replacements\":\"\"},\"title\":{\"text\":\"Title\",\"color\":\"#434761\",\"replacements\":\"\"},\"buttons\":[{\"text\":\"Button\",\"color\":\"#000000\",\"bg\":\"#1EB858\",\"border\":\"#1EB858\",\"radius\":\"4\",\"actions\":{\"close\":true,\"type\":\"kv\",\"android\":\"\",\"ios\":\"\",\"kv\":[{\"key\":\"\\\"id\\\"\",\"value\":{\"text\":\"123\",\"og\":\"123\",\"replacements\":\"123\",\"key\":\"\",\"df\":{},\"defaultValuesSet\":{\"value\":true,\"strict\":true}}},{\"key\":\"\\\"name\\\"\",\"value\":{\"text\":\"\\\"John Doe\\\"\",\"og\":\"\\\"John Doe\\\"\",\"replacements\":\"\\\"John Doe\\\"\",\"key\":\"\",\"df\":{},\"defaultValuesSet\":{\"value\":true,\"strict\":true}}}]}}],\"media\":{},\"isMediaSourceRecommended\":false,\"recommendedText\":{\"text\":\"\",\"replacements\":\"\",\"og\":\"\"},\"mediaLandscape\":{},\"isMediaSourceRecommendedLandscape\":false,\"recommendedTextLandscape\":{\"text\":\"\",\"replacements\":\"\",\"og\":\"\"},\"hasPortrait\":true,\"hasLandscape\":false}"},"2":{"wzrk_inapp":"{\"type\":\"cover\",\"bg\":\"#ffffff\",\"tablet\":false,\"close\":true,\"message\":{\"text\":\"Message\",\"color\":\"#434761\",\"replacements\":\"\"},\"title\":{\"text\":\"Title\",\"color\":\"#434761\",\"replacements\":\"\"},\"buttons\":[{\"text\":\"Button\",\"color\":\"#000000\",\"bg\":\"#1EB858\",\"border\":\"#1EB858\",\"radius\":\"4\",\"actions\":{\"close\":true,\"type\":\"kv\",\"android\":\"\",\"ios\":\"\",\"kv\":[{\"key\":\"\\\"id\\\"\",\"value\":{\"text\":\"123\",\"og\":\"123\",\"replacements\":\"123\",\"key\":\"\",\"df\":{},\"defaultValuesSet\":{\"value\":true,\"strict\":true}}},{\"key\":\"\\\"name\\\"\",\"value\":{\"text\":\"\\\"John Doe\\\"\",\"og\":\"\\\"John Doe\\\"\",\"replacements\":\"\\\"John Doe\\\"\",\"key\":\"\",\"df\":{},\"defaultValuesSet\":{\"value\":true,\"strict\":true}}}]}}],\"media\":{},\"isMediaSourceRecommended\":false,\"recommendedText\":{\"text\":\"\",\"replacements\":\"\",\"og\":\"\"},\"mediaLandscape\":{},\"isMediaSourceRecommendedLandscape\":false,\"recommendedTextLandscape\":{\"text\":\"\",\"replacements\":\"\",\"og\":\"\"},\"hasPortrait\":true,\"hasLandscape\":false}"},"3":{"wzrk_inapp":"{\"type\":\"cover\",\"bg\":\"#ffffff\",\"tablet\":false,\"close\":true,\"message\":{\"text\":\"Message\",\"color\":\"#434761\",\"replacements\":\"\"},\"title\":{\"text\":\"Title\",\"color\":\"#434761\",\"replacements\":\"\"},\"buttons\":[{\"text\":\"Button\",\"color\":\"#000000\",\"bg\":\"#1EB858\",\"border\":\"#1EB858\",\"radius\":\"4\",\"actions\":{\"close\":true,\"type\":\"kv\",\"android\":\"\",\"ios\":\"\",\"kv\":[{\"key\":\"\\\"id\\\"\",\"value\":{\"text\":\"123\",\"og\":\"123\",\"replacements\":\"123\",\"key\":\"\",\"df\":{},\"defaultValuesSet\":{\"value\":true,\"strict\":true}}},{\"key\":\"\\\"name\\\"\",\"value\":{\"text\":\"\\\"John Doe\\\"\",\"og\":\"\\\"John Doe\\\"\",\"replacements\":\"\\\"John Doe\\\"\",\"key\":\"\",\"df\":{},\"defaultValuesSet\":{\"value\":true,\"strict\":true}}}]}}],\"media\":{},\"isMediaSourceRecommended\":false,\"recommendedText\":{\"text\":\"\",\"replacements\":\"\",\"og\":\"\"},\"mediaLandscape\":{},\"isMediaSourceRecommendedLandscape\":false,\"recommendedTextLandscape\":{\"text\":\"\",\"replacements\":\"\",\"og\":\"\"},\"hasPortrait\":true,\"hasLandscape\":false}"}},"id":"","appId":0}

JSON received on `wzrk_inapp` key
> @"{ \"type\" : \"cover\" , \"bg\" : \"#ffffff\" , \"tablet\" : false , \"close\" : true , \"message\" : { \"text\" : \"Message\" , \"color\" : \"#434761\" , \"replacements\" : \"\"} , \"title\" : { \"text\" : \"Title\" , \"color\" : \"#434761\" , \"replacements\" : \"\"} , \"buttons\" : [ { \"text\" : \"Button\" , \"color\" : \"#000000\" , \"bg\" : \"#1EB858\" , \"border\" : \"#1EB858\" , \"radius\" : \"4\" , \"actions\" : { \"close\" : true , \"type\" : \"kv\" , \"android\" : \"\" , \"ios\" : \"\"}}] , \"media\" : { } , \"isMediaSourceRecommended\" : false , \"recommendedText\" : { \"text\" : \"\" , \"replacements\" : \"\" , \"og\" : \"\"} , \"mediaLandscape\" : { } , \"isMediaSourceRecommendedLandscape\" : false , \"recommendedTextLandscape\" : { \"text\" : \"\" , \"replacements\" : \"\" , \"og\" : \"\"} , \"hasPortrait\" : true , \"hasLandscape\" : false}"	0x0000000115f20490

**Comment by Aditi3** [comment]
Hi @gusparis We're investigating this issue at the moment. I will get back to you with an update shortly.

**Comment by darshanclevertap** [comment]
@gusparis There was a bug in the "Send Test InApp" flow which was sending the wrong JSON payload to the SDK. This is being fixed by our back end teams right now. I'll keep you updated when this is fixed and deployed.

**Comment by gusparis** [comment]
Thanks for your quick response.

**Comment by Aditi3** [comment]
@gusparis This is fixed and deployed to the production. 

Thank you for your patience here.

**Comment by gusparis** [comment]
Thank you!
