### ISSUE TITLE
 CleverTap.registerForPush(); callback

### ISSUE THREAD

**Issue by melvinmt** [CleverTap/clevertap-react-native#128]
We need to tell if registerForPush succeeded or not, how can I tell if the user accepted the push notifications when I use CleverTap.registerForPush(). Is there a callback that I can use?

**Comment by Aditi3** [comment]
Hi @melvinmt 

CleverTap **[registerForPush](https://github.com/CleverTap/clevertap-react-native/blob/master/ios/CleverTapReact/CleverTapReact.m#L70)** internally only call the registerForRemoteNotifications() method of UIApplication to request the device token. 

I would recommend adding the following methods provided by Apple in your App Delegate class to know if the device token of a user has been successfully registered or not.

```
func application(_ application: UIApplication,
            didRegisterForRemoteNotificationsWithDeviceToken 
                deviceToken: Data) {
  // Called upon successful registration
}

func application(_ application: UIApplication,
            didFailToRegisterForRemoteNotificationsWithError 
                error: Error) {
     // Called upon unsuccessful registration
}
```

Helpful link: https://developer.apple.com/documentation/usernotifications/registering_your_app_with_apns

**Comment by Aditi3** [comment]
Closing it, feel free to reopen if you need further help.

**Comment by jfbn** [comment]
> Hi @melvinmt
> 
> CleverTap **[registerForPush](https://github.com/CleverTap/clevertap-react-native/blob/master/ios/CleverTapReact/CleverTapReact.m#L70)** internally only call the registerForRemoteNotifications() method of UIApplication to request the device token.
> 
> I would recommend adding the following methods provided by Apple in your App Delegate class to know if the device token of a user has been successfully registered or not.
> 
> ```
> func application(_ application: UIApplication,
>             didRegisterForRemoteNotificationsWithDeviceToken 
>                 deviceToken: Data) {
>   // Called upon successful registration
> }
> 
> func application(_ application: UIApplication,
>             didFailToRegisterForRemoteNotificationsWithError 
>                 error: Error) {
>   // Called upon unsuccessful registration
> }
> ```
> 
> Helpful link: https://developer.apple.com/documentation/usernotifications/registering_your_app_with_apns

Thank you for this response. I too would like to be able to pass a callback to the `registerForPush` method to know if the registration was successfull or not.

For those of us that are only React-Native devs and don't know the internals of the native side, how would I go about exposing the result from your suggestion to the React-Native side of things?
