### ISSUE TITLE
How to get AB testing key in app ?

### ISSUE THREAD

**Issue by kmgaurav2611** [CleverTap/clevertap-react-native#130]
Hi All,

I have created an A/B testing setup and created keys, segments and goals for it. I am not able to receive the key when I call the  CleverTap.getListOfStringVariable function.

My Key Name is "Button Color" whose default value is 'yellow'(string). I am calling as follows:

 `CleverTap.getListOfStringVariable("Button Color",["pink","orange"], (err, res) => {
            console.log('List of String Dynamic Variables in res: ', res, err);
        });`

I am getting ["pink","orange"] as output.

**Comment by Aditi3** [comment]
hi @kmgaurav2611 

We've deprecated Dynamic Variable Feature. I request you to write to our support team with the use-case. Someone from our support team will help you with the alternate/ equivalent [features](https://docs.clevertap.com/docs/product-experiences) available.

Thank you!

**Comment by Cshayan** [comment]
@kmgaurav2611 Use the getProductConfigString() method to fetch the A/B testing key values.  Create a utility function and call this anywhere you require.

```
export const getConfigStringValue = key =>
    new Promise((resolve, reject) => {
        CleverTap.getProductConfigString(key, (err, obj) => {
            if (err) reject(err);
            resolve(obj);
        });
    });
```
Then call it using async-await syntax.

```
  const fetchABValue = async (key) => {
       const data = await getConfigStringValue(key); // key is the name of the key set in Clevertap dashoard
       console.log(data); // will print the value of the key
  };
```
Make sure the A/B testing is published live and that key you are fetching is being used in that A/B test.

**Note:**
For this to work, you need to call fetch() and activate() method of Clevertap when your app loads and initializes. 

 ```
CleverTap.fetch();
CleverTap.activate();
```

**Comment by Aditi3** [comment]
Closing it, feel free to reopen if you need further help.
