### ISSUE TITLE
Geofencing Integration in React Native

### ISSUE THREAD

**Issue by HammzaHM** [CleverTap/clevertap-react-native#133]
Hello there,
I am working on React Native project where we've implemented  CleverTap for uploading user events. Recently, I have a task of integrating CleverTap Geofencing in our application in order to take advantage of this feature. 
Unfortunately there is no integration instructions for react native CT SDK.

**Comment by piyush-kukadiya** [comment]
@HammzaHM We are planning to add support for this feature in React Native in upcoming release.

**Comment by HammzaHM** [comment]
@piyush-kukadiya  Thank you for your reply Sir.
I hope this release is soon to be published because this feature is **very important and crucial for our application**
