### ISSUE TITLE
On push notification click , first redirecting to web then  to app

### ISSUE THREAD

**Issue by CHANDRAMOHANnegi** [CleverTap/clevertap-react-native#134]
On push notification click , first redirecting to web then  to app.
sometime it directly redirects to app .

I want it to redirect to app .

**Comment by piyush-kukadiya** [comment]
@CHANDRAMOHANnegi on iOS or Android or both? Also mention SDK versions.

**Comment by CHANDRAMOHANnegi** [comment]
We were using web url , and not deeplinking url 

it is sorted now
