### ISSUE TITLE
iOS: Failed to send out test notification(s) : APNSBadDeviceToken (1)

### ISSUE THREAD

**Issue by CHANDRAMOHANnegi** [CleverTap/clevertap-react-native#136]
iOS: Failed to send out test notification(s) :
APNSBadDeviceToken (1)

I am able to get notification with clevertap test credentials when my ios phone is connected to xcode

but , I am getting this error While sending with prod credentials . i installed ipa in my ios device

**Comment by CHANDRAMOHANnegi** [comment]
@Aditi3

**Comment by Aditi3** [comment]
Hi @CHANDRAMOHANnegi 

The error specifies device token was bad. You get this error when you try to send the notification with the wrong certificate/  authentication token.

I would recommend verifying the configuration of the CleverTap dashboard. It should be APNs push mode: Development/ Production with a valid development/ production certificate or authentication token in Push Setting for iOS.

Thank you!
