### ISSUE TITLE
Branch.IO and Clevertap Integration issue ($clevertap_attribution_id is not getting sent to Branch)

### ISSUE THREAD

**Issue by Cshayan** [CleverTap/clevertap-react-native#138]
Hey, I am integrating Branch.IO and Clevertap in react-native app following these docs: 

[https://help.branch.io/using-branch/page/clevertap](url) 
[https://developer.clevertap.com/docs/branch](url)

In the docs, for Android it is mentioned to call the `setRequestMetadata()` of Branch to pass the `$clevertap_attribution_id` before Branch's initSession is being called.

However, I can see in many cases the attribution id is not getting passed to Branch metadata while Branch SDK is calling their Install API. See the below log ->

```
Posting to https://api2.branch.io/v1/install
2021-03-04 12:47:01.788 26322-26440/someapp.in.random.app I/BranchSDK: Post value = {"hardware_id":"394526592407b3a6","is_hardware_id_real":true,"brand":"Google","model":"Android SDK built for x86","screen_dpi":420,"screen_height":1794,"screen_width":1080,"wifi":false,"ui_mode":"UI_MODE_TYPE_NORMAL","os":"Android","os_version":29,"cpu_type":"i686","build":"sdk_gphone_x86-userdebug 10 QSR1.200715.002 6695061 dev-keys","locale":"en_US","connection_type":"mobile","device_carrier":"Android","os_version_android":"10","country":"US","language":"en","local_ip":"10.0.2.15","app_version":"1.93","facebook_app_link_checked":false,"is_referrable":0,"debug":false,"update":0,"latest_install_time":1614842064980,"latest_update_time":1614842064980,"first_install_time":1614842064980,"previous_update_time":0,"environment":"FULL_APP","metadata":{},"advertising_ids":{"aaid":"c8083e6f-8b8e-4431-a38d-2925e918b2a9"},"lat_val":0,"google_advertising_id":"c8083e6f-8b8e-4431-a38d-2925e918b2a9","instrumentation":{"v1\/install-qwt":"0"},"sdk":"android5.0.3","branch_key":"<branch_live_key>"}
```
Hence while Branch is calling the Clevertap's webhook, Clevertap is returning 400 response.

![Screenshot (35)_LI](https://user-images.githubusercontent.com/45463444/110664102-2309a900-81ed-11eb-9b36-29d6eaa2037f.jpg)

Below is an overview of my approach ->

`MainActivity.java`

```
import com.clevertap.android.sdk.CleverTapAPI;
import io.branch.rnbranch.RNBranchModule;

public class MainActivity extends ReactActivity {
    CleverTapAPI cleverTapAPI;

    .....
    
    @Override
    protected void onStart() {
       super.onStart();
       Branch.enableLogging();
       cleverTapAPI = CleverTapAPI.getDefaultInstance(getApplicationContext());
       if (cleverTapAPI != null) {
           String clevertapId = cleverTapAPI.getCleverTapAttributionIdentifier();
           RNBranchModule.setRequestMetadata("$clevertap_attribution_id", clevertapId);
       } else {
           Log.e("clevertap branch integration","CleverTap is NULL during branch init session");
       }
       RNBranchModule.initSession(getIntent().getData(), this);
    }
    
     @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        RNBranchModule.onNewIntent(intent);
    }
}
```

`MainApplication.java`

```
import io.branch.rnbranch.RNBranchModule;

public class MainApplication extends Application implements ReactApplication {
 
     @Override
      public void onCreate() {
          super.onCreate();
         RNBranchModule.getAutoInstance(this);
      }
}           
```

Additional info:

Branch Android SDK version: 5.0.4
Clevertap Android SDK version: 3.9.0

**Note:** This issue is happening for most users, but sometimes the attribution_id is getting passed to Branch and in that case I am seeing 200 response when Branch calls Clevertap's webhook.

Any help/suggestion on how to proceed for this will be appreciated. Thank you!

**Comment by Cshayan** [comment]
@darshanclevertap @Aditi3 any update guys on this issue?

**Comment by piyush-kukadiya** [comment]
@Cshayan When you call `cleverTapAPI.getCleverTapAttributionIdentifier()` do you get null value?

**Comment by Cshayan** [comment]
@piyush-kukadiya Yes, sometimes it gives null value, and sometimes it gives the value of the id.

**Comment by piyush-kukadiya** [comment]
@Cshayan Are you using `googleAdId` ? and what is `clevertap-react-native` version?

**Comment by Cshayan** [comment]
@piyush-kukadiya Yes I am passing GAID/AAID to Branch. And the clevertap-react-native version is 0.5.0.

**Comment by Cshayan** [comment]
@piyush-kukadiya Any update on the issue?

**Comment by piyush-kukadiya** [comment]
@Cshayan Use `CleverTapProfileDidInitialize` callback and look for CT attribution ID on that callback and then give it to Branch. `CleverTapProfileDidInitialize` will make sure that` cleverTapAPI.getCleverTapAttributionIdentifier()` value is non-null.

**Comment by Cshayan** [comment]
@piyush-kukadiya Thanks for the update. Is there any docs or code snippet on how to use this? I am not getting anything related to `CleverTapProfileDidInitialize` callback in the documentation.

**Comment by Cshayan** [comment]
@piyush-kukadiya Please provide any link of docs for the above implementation.

**Comment by piyush-kukadiya** [comment]
https://github.com/CleverTap/clevertap-react-native/blob/master/Starter/App.js#L50

**Comment by Cshayan** [comment]
@piyush-kukadiya I am writing the logic of sending the clevertap attribution id in Native side in Java, but the link you provided is in JavaScript. Can't we not implement this callback logic in Native side using Java?

**Comment by Cshayan** [comment]
@piyush-kukadiya Any update on how to implement the above callback in native side using Java? The link you shared has to be implemented in JavaScript side which is not the correct place to send the attribution id.

**Comment by piyush-kukadiya** [comment]
@Cshayan Try this out https://github.com/CleverTap/clevertap-android-sdk/blob/master/clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java#L2255

**Comment by piyush-kukadiya** [comment]
@Cshayan Did this work for you?

**Comment by piyush-kukadiya** [comment]
Closing as inactive
