### ISSUE TITLE
Deeplinking not working on click on notification when app is closed

### ISSUE THREAD

**Issue by CHANDRAMOHANnegi** [CleverTap/clevertap-react-native#141]
When app is in background , i am able to receive notification and on click on notification , deeplinking  redirect to correct screen.

when app is in foreground , open   , then i am not receiving notification

when app is closed then on click on notification  , app is opening but not redirecting to correct screen . means it just opens app

**Comment by Aditi3** [comment]
Please refer to the response here - https://github.com/CleverTap/clevertap-react-native/issues/125#issuecomment-742427995

Duplicate of #125

**Comment by Aditi3** [comment]
Closing this thread.
