### ISSUE TITLE
can not build ios project

### ISSUE THREAD

**Issue by clind-arthur** [CleverTap/clevertap-react-native#147]
/Users/clind/clind/clind-phoenix/node_modules/clevertap-react-native/ios/CleverTapReact/CleverTapReactManager.m:11:9: fatal error: 'CleverTap+ABTesting.h' file not found
#import "CleverTap+ABTesting.h"
        ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

"clevertap-react-native": "^0.5.0" with  CleverTap-iOS-SDK (3.9.3) on Podfile.lock

**Comment by Aditi3** [comment]
@clind-arthur, Can you please try downgrading CleverTap iOS SDK to version 3.9.2 or below by specifying the following code in your podfile:

`pod 'CleverTap-iOS-SDK', '3.9.2'`

We have removed support for the deprecated Dynamic Variable and Visual Editor, part of the CleverTap+ABTesting.h header in the latest 3.9.3 which is resulting in the error for you. We have a plan to incorporate the same change in our React Native SDK. 

For now, I recommend trying the above change to resolve the error. Apologies for the inconvenience caused.

**Comment by Pierre-CLIND** [comment]
Thx @Aditi3 And How can we do this on a ReactNative project?

Because on Podile we have:

`  pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native'
`

**Comment by Aditi3** [comment]
@Pierre-CLIND yes, you can.

**Comment by LonelyCpp** [comment]
Why would this major change in ios-sdk be released as a **patch** update!? The ios-sdk pod should have been released as a major release (minor at least) to prevent pod from auto-upgrading ☹️ 

IMO `~>` should be removed to enforce the pod version here https://github.com/CleverTap/clevertap-react-native/blob/53e627ce896a560437b2b3c3847ba35c9f746431/clevertap-react-native.podspec#L21

**Comment by AndrewMorsillo** [comment]
Why was a breaking change released as a patch update? This cost me valuable time today.

**Comment by clind-arthur** [comment]
just tested to remove pod 'CleverTap-iOS-SDK', '3.9.2' 
under pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native'
and pod update

and the issue is still there.

**Comment by Vishal0201** [comment]
@clind-arthur yes its not resolved yet, i am still getting the same issue.

**Comment by Aditi3** [comment]
Hi @Vishal0201 @clind-arthur 

Did you update to our latest release [v0.5.1](https://github.com/CleverTap/clevertap-react-native/releases/tag/0.5.1)?
It working fine at our end and in our [Starter Project](https://github.com/CleverTap/clevertap-react-native/tree/master/Starter).

**Comment by LonelyCpp** [comment]
works for me. (you have to update the version in package.json to 0.5.1, and run pod update)

**Comment by Vishal0201** [comment]
> Hi @Vishal0201 @clind-arthur
> 
> Did you update to our latest release [v0.5.1](https://github.com/CleverTap/clevertap-react-native/releases/tag/0.5.1)?
> 
> It's working fine at our end and in our [Starter Project](https://github.com/CleverTap/clevertap-react-native/tree/master/Starter).

yes its working now !

**Comment by akshayjai1** [comment]
yes, simply upgrading to clevertap-react-native 0.5.1 works
