### ISSUE TITLE
Xiomi push notification

### ISSUE THREAD

**Issue by CHANDRAMOHANnegi** [CleverTap/clevertap-react-native#148]
I have done following configuration for xiomi push notification

  1 .  https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTXIAOMIPUSH.md

  2 .  implementation 'com.clevertap.android:clevertap-xiaomi-sdk:1.0.0'     => in app build gradle

but this is not working

@Aditi3 

i am not  adding MiPush_SDK_Client_3_8_6 .

should i add this

**Comment by piyush-kukadiya** [comment]
@CHANDRAMOHANnegi `MiPush_SDK_Client_3_8_6`  is already added by CleverTap. What issue you are facing. Also tell us what sdk version are you using for `clevertap-react-native`, `clevertap-android-sdk` .

**Comment by piyush-kukadiya** [comment]
Closing as inactive
