### ISSUE TITLE
iOS notification with DeepLink issue 

### ISSUE THREAD

**Issue by vipulRajput** [CleverTap/clevertap-react-native#149]
@Aditi3 

Hi I followed all the iOS dev-Docs steps to integrate the CleverTap but I'm facing issue regarding notification with deeplink:- 

* I'm getting notifications in all cases (when when is terminated, in foreground or in background).
* But when I click on notification, it just triggers app then quickly redirects to safari (instead it should redirect user to required screen)  

Please help me on this :( .

**Comment by Aditi3** [comment]
I am assuming that you want to understand why your deeplink is opening in the browser. Here's a brief understanding of how deep links works on the iOS platform.

There are two types of Deeplinks:

1. External: typically of the type http/https, which redirect you externally (out of the app) to a certain web page/website. 
2. Internal: This deep link is configured by the app developer in the app, can be configured on any page/activity as you desire, for example, form: app://open.my.app (can also begin with https) and used to opening any particular part inside the App. 

Also explaining some default behaviour and solutions below:
* For iOS:
    * If the push notification has a deep link with an http/https URL, it invokes the app. Later it will be redirected to the browser. This is default behaviour at the OS level.
    * Please check out this [documentation](https://developer.apple.com/documentation/xcode/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app) for reference.
    * You can also pass the HTTPS: deep link as a custom key-value pair while creating the Push Campaign. In your app then you can read the custom key-value pair and decide the redirection logic. Helping documentation can be found [here](https://developer.clevertap.com/docs/ios#section-push-notification-callback).

**Comment by Aditi3** [comment]
@vipulRajput Closing this issue here as it is being taken by our support team.
