### ISSUE TITLE
Need Update for CleverTap React Native SDK to Support Core SDK-4.1.0 

### ISSUE THREAD

**Issue by sangupandi** [CleverTap/clevertap-react-native#152]
**Need Update for CleverTap React Native SDK to Support Core SDK-4.1.0** 

Xioami &  huawei push service tokens were not switched to new profiles in Clevertap, For these we need to update the Core CleverTap SDK to 4.1.0 .

I am using clevertap react native version :-0.5.0  { It is not supporting the Latest Core SDK version } , Kindly release the upgraded
react native clevertap SDK version as soon as possible.

**Comment by darshanclevertap** [comment]
@sangupandi We're working on updating our React Native SDK to support CT Android SDK v4.1.0 and we'll be releasing it as soon as possible

**Comment by piyush-kukadiya** [comment]
@sangupandi Update to `0.5.1`
