### ISSUE TITLE
            variable HmsInstanceId   not found

### ISSUE THREAD

**Issue by CHANDRAMOHANnegi** [CleverTap/clevertap-react-native#159]
```
cannot find symbol
    String token = HmsInstanceId.getInstance(MainActivity.this).getToken(AppId, "HCM");
                   ^
  symbol:   variable HmsInstanceId
  location: class MainActivity
  
```  
  https://developer.clevertap.com/docs/clevertap-huawei-push-integration#section-pass-token-to-clever-tap
  
For HUAWEI INTEGRATION  i have done.
I have added configuration for root and app level build gradle ,and added `  agconnect-services.json` to app root only .

```

String appId = AGConnectServicesConfig.fromContext(MainActivity.this).getString("client/app_id");
String token = HmsInstanceId.getInstance(MainActivity.this).getToken(appId, "HCM");
```
  
added these lines to create method , but dont know from where I will get these variables
AGConnectServicesConfig and HmsInstanceId

    @Aditi3 
   i am using
    "clevertap-react-native": "^0.5.0"
    implementation 'com.clevertap.android:clevertap-android-sdk:4.0.1'

**Comment by piyush-kukadiya** [comment]
@CHANDRAMOHANnegi Did you added hms dependency?

**Comment by CHANDRAMOHANnegi** [comment]
IFor HUAWEI INTEGRATION i have done.
I have added configuration for root and app level build gradle ,and added agconnect-services.json to app root only .

what import statement should i use in MainActivity , to import AGConnectServicesConfig and HmsInstanceId
@piyush-kukadiya

**Comment by CHANDRAMOHANnegi** [comment]
do i have to create a Push service class which will extend HmsMessageService class.

**Comment by CHANDRAMOHANnegi** [comment]
import com.huawei.agconnect.config.AGConnectServicesConfig;
import com.huawei.hms.aaid.HmsInstanceId;

**Comment by CHANDRAMOHANnegi** [comment]
import com.huawei.agconnect.config.AGConnectServicesConfig;
import com.huawei.hms.aaid.HmsInstanceId;

**Comment by CHANDRAMOHANnegi** [comment]
import com.huawei.agconnect.config.AGConnectServicesConfig;
import com.huawei.hms.aaid.HmsInstanceId;
