### ISSUE TITLE
error: cannot find symbol CleverTapAPI.setUIEditorConnectionEnabled(false)

### ISSUE THREAD

**Issue by ShubhamBathe-KM** [CleverTap/clevertap-react-native#161]
I am getting this error all of a sudden while trying to run or create a debug build for android. It was working fine 2 days ago. I am using latest version of clevertap npm package(v 0.5.1). Please help me resolve this as soon as possible. Attaching a screenshot of error message on android studio for your reference.

I have done these imports in MainApplication.java file:-

```
// CleverTap imports
import com.clevertap.android.sdk.ActivityLifecycleCallback; 
import com.clevertap.react.CleverTapPackage; 
import com.clevertap.android.sdk.CleverTapAPI;

```
These are my project specific details:-
```
"react": "16.11.0",
"react-native": "0.62.2",
"clevertap-react-native": "^0.5.1",
```
I have followed all the installation & integration steps as mentioned in the documentation.

Thanks & Regards.

<img width="899" alt="Screenshot at May 13 12-59-03" src="https://user-images.githubusercontent.com/67695272/118093805-96958580-b3eb-11eb-9ed6-1d2117ee8880.png">

**Comment by piyush-kukadiya** [comment]
@ShubhamBathe-KM We have removed Product experiences(Dynamic Variables) feature from `0.5.1` onwards.
https://github.com/CleverTap/clevertap-react-native/blob/master/CHANGELOG.md#version-051-5th-may-2021

**Comment by piyush-kukadiya** [comment]
You must remove that feature from your code

**Comment by ShubhamBathe-KM** [comment]
@piyush-kukadiya Thanks for your quick response. So as you told I commented out this code 
`// CleverTapAPI.setUIEditorConnectionEnabled(false);` but now my app is crashing just after its gets launched. I also tried to downgrade "clevertap-react-native" to version "^0.5.0". Still getting the same error.

**Comment by frzkn** [comment]
I also faced the same issue, I fixed it by downgrading to ```0.5.0```
    `"clevertap-react-native": "0.5.0"`

The version ```0.5.1``` introduced a breaking change which isn't backwards compatible therefore I think there should've been a major version bump, Kindly follow correct semantic versioning as I think this update broke a lot of apps using this library.

**Comment by ShubhamBathe-KM** [comment]
@frzkn I tried this `"clevertap-react-native": "0.5.0"` as well. Didn't work for me. Need some concrete solution for this problem.

**Comment by piyush-kukadiya** [comment]
@ShubhamBathe-KM can you post error stack trace

**Comment by ShubhamBathe-KM** [comment]
Sure @piyush-kukadiya
**Here is the error stack trace from terminal:-**

<img width="971" alt="Screenshot at May 13 22-20-11" src="https://user-images.githubusercontent.com/67695272/118158608-a50a8e00-b439-11eb-95cb-a4dbcbaf842e.png">

**Also sending same in text format:-**

/Users/webwerks/Desktop/Shubham/KM/pnp2-rn-app/android/app/src/main/java/com/khelomore/pnp/MainApplication.java:58: error: cannot find symbol
    CleverTapAPI.setUIEditorConnectionEnabled(false);
    ^
  symbol:   variable CleverTapAPI
  location: class MainApplication
/Users/webwerks/Desktop/Shubham/KM/pnp2-rn-app/android/app/src/main/java/com/khelomore/pnp/MainActivity.java:24: error: cannot access CTExperimentsListener
    CleverTapModule.setInitialUri(getIntent().getData());
                   ^
  class file for com.clevertap.android.sdk.CTExperimentsListener not found
/Users/webwerks/Desktop/Shubham/KM/pnp2-rn-app/android/app/src/main/java/com/khelomore/pnp/MainActivity.java:25: error: cannot find symbol
    CleverTapAPI clevertapDefaultInstance = CleverTapAPI.getDefaultInstance(getApplicationContext());
    ^
  symbol:   class CleverTapAPI
  location: class MainActivity
/Users/webwerks/Desktop/Shubham/KM/pnp2-rn-app/android/app/src/main/java/com/khelomore/pnp/MainActivity.java:25: error: cannot find symbol
    CleverTapAPI clevertapDefaultInstance = CleverTapAPI.getDefaultInstance(getApplicationContext());
                                            ^
  symbol:   variable CleverTapAPI
  location: class MainActivity
Note: /Users/webwerks/Desktop/Shubham/KM/pnp2-rn-app/android/app/src/debug/java/com/dreamxboilerplate/ReactNativeFlipper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 4s

Thanks & Regards.
Waiting for a solution....

**Comment by gusparis** [comment]
> @ShubhamBathe-KM We have removed Product experiences(Dynamic Variables) feature from `0.5.1` onwards.
> https://github.com/CleverTap/clevertap-react-native/blob/master/CHANGELOG.md#version-051-5th-may-2021

You should update your readme with this information.

**Comment by piyush-kukadiya** [comment]
https://user-images.githubusercontent.com/61137760/118243313-ee032680-b4bb-11eb-993f-a59603f9f285.mov

@gusparis We have added information regarding removing code related to Product Experience (Dynamic Vars) in our Release Notes and ChangeLog. Still, if it caused inconvenience to you then sorry for that.

@ShubhamBathe-KM , We have verified the installation and integration of the latest version in our test application and it worked for us as attached in video. For more support you can reach the support team from Dashboard. This will help in resolving the issue faster.

**Comment by ShubhamBathe-KM** [comment]
@piyush-kukadiya Thanks for the video support. I was able to successfully run my project now after making the needed changes. Just request you to update the documentation and example project in the repository as soon as possible. That would be really great!!
