### ISSUE TITLE
Not able to invoke event listener on CleverTap.CleverTapPushNotificationClicked 

### ISSUE THREAD

**Issue by pranshuchittora** [CleverTap/clevertap-react-native#167]
Hi,
I am trying to listen to the notification click by referencing the provided starter project. Unfortunately, the callback is not getting invoked on click.
```js
   CleverTap.addListener(CleverTap.CleverTapPushNotificationClicked, event => {
      ...
    });
```

https://user-images.githubusercontent.com/32242596/123094031-09ae0500-d44a-11eb-8fee-379f21a10a3f.mov

Let me know if I am doing anything wrong here.

**Comment by piyush-kukadiya** [comment]
@pranshuchittora You get this callback only when app is running, if you want it when app is in killed state then use this workaround => https://github.com/CleverTap/clevertap-react-native/commit/be647bab97081bbec8d8a8d7faaaa944bf4a877f

**Comment by pranshuchittora** [comment]
@piyush-kukadiya thanks for quick response.

> You get this callback only when app is running
I tried this but it is not getting invoked even when the app is running (in foreground )

For the native workaround is there any way to abstract this process inside CT-React Native SDK because applying this native workaround requires some good amount of maintainability. And the whole idea of RN is to abstract the native part as much as possible.

**Comment by piyush-kukadiya** [comment]
@pranshuchittora For foreground case it's working for me.  Regarding abstract out native workaround, if possible we will do that based on other priorities and let you know once we release the same. 

https://user-images.githubusercontent.com/61137760/123269923-0e8fb900-d51d-11eb-83a9-ab6f5ae79c52.mov

**Comment by pranshuchittora** [comment]
@piyush-kukadiya I upgrade my CT SDK to v4 and it is working when the app is in the foreground but only for notifications sent via CT campaigns not from firebase cloud messaging.

Is there any way to handle click for notifications **not sent with CT campaigns** (like firebase or FCM API)?

**Comment by piyush-kukadiya** [comment]
@pranshuchittora I assume you must be using plugin for non CleverTap push providers who will provide click functionality.

Refer this if you want custom handling https://developer.clevertap.com/docs/android#section-custom-android-push-notifications-handling

**Comment by Aditi3** [comment]
Closing it, feel free to reopen if you need further help.
