### ISSUE TITLE
Multiple CleverTap ID's issue for a single user

### ISSUE THREAD

**Issue by Md-Mudassir47** [CleverTap/clevertap-react-native#175]
The **onUserLogin** method is generating multiple Id's when a user logs out and then login back its identifying it as a separate entity..why? also why there's no **onUserLogsOut** method? by which it will clear out the reference of the existing user and when a new user tries to log in it wont conflict with the previous user.

`` CleverTap.onUserLogin({
            Identity: response.id,
            Name: response.fullName,
            Email: response.emailId,
            Phone: response?.phoneNumber,
          });``

<img width="506" alt="Screenshot 2021-08-17 at 11 53 57 AM" src="https://user-images.githubusercontent.com/85115578/129674308-417d18e0-1d63-4e8b-8e5a-efe3a5498d49.png">

**Comment by Aditi3** [comment]
Hi @Md-Mudassir47 Here's the brief documentation about how CleverTap manages user identity - https://docs.clevertap.com/docs/how-profiles-merge

If you have more queries around the same I request you to write to our support team with your use case.
