### ISSUE TITLE
Unable to update push notification setting and receive push notifications

### ISSUE THREAD

**Issue by AnilG1793** [CleverTap/clevertap-react-native#18]
I am unable to get push notification on my device while integrated plugin. I already asked questions on [Stackoverflow](https://stackoverflow.com/questions/52515516/react-native-clevertap-push-notification-integration) and [Clevertap community](https://community.clevertap.com/t/unable-to-receive-push-notification-on-device/1818).

I have tried with native android example its working fine, but incase of react native Push notification option is not enabled at all.

**Comment by Aditi3** [comment]
Hey @AnilG1793 

Can you ensure you are calling the 

 // for iOS only: register for push notifications
`        CleverTap.registerForPush();`

to register push notifications ?

**Comment by AnilG1793** [comment]
@darshanclevertap , When I am trying to update profile its showing, that profile request is queued. And when queue request is make its throwing timeout exception.

**Comment by AnilG1793** [comment]
@darshanclevertap , **One more thing I have observed today**, When I am trying to fetch **MSG-push property** of created user profile, it's returning me as true. But when trying to cross verify with Dashboard its not matching. On dashboard Push notification showing as disabled(false).
Here is a log :- 
`09-28 12:29:56.284 11860-12369/com.clevertapexample I/ReactNativeJS: 'CleverTap Profile Name: ', 'UserA', null
09-28 12:29:56.286 11860-12369/com.clevertapexample I/ReactNativeJS: 'CleverTap Push Msg: ', true, null
`

**Comment by tanviagarwaltravel** [comment]
Is there any listener which gets called in react-native when we click on notifications?
