### ISSUE TITLE
App Crashing on Android on start when integrating clevertap

### ISSUE THREAD

**Issue by tanveersalmangkn** [CleverTap/clevertap-react-native#192]
I have integrated clevertap in my react native app. it's working fine on iOS and making the app on android side crash on every start. Getting these couple of errors
**TypeError: null is not an object (evaluating 'CleverTapReact.CleverTapProfileDidInitialize')**
**Invariant Violation: Module AppRegistry is not a registered callable m
<img width="914" alt="Screen Shot 2021-09-30 at 1 10 31 PM" src="https://user-images.githubusercontent.com/51949068/135413550-85523d8e-7e6d-4482-ac3d-57b34e1aa749.png">
odule (calling runApplication**

Please help me here

**Comment by piyush-kukadiya** [comment]
@tanveersalmangkn I would suggest you to look at sample project for proper understanding of usage. Same thing is working in our sample app.

**Comment by tanveersalmangkn** [comment]
@piyush-kukadiya I tried that as well but same. Could you please help me out here? I don't know whats wrong. Working for iOS but not android.

**Comment by piyush-kukadiya** [comment]
@tanveersalmangkn Can you share sample app where issue is reproducible?

**Comment by tanveersalmangkn** [comment]
App keeps crashing on the start, I have followed the example app as well and did all the stuff which was mentioned there.
<img width="709" alt="Screen Shot 2021-09-30 at 3 15 45 PM" src="https://user-images.githubusercontent.com/51949068/135437120-a791e99e-3a45-4a0e-9d8c-57fa7cc6c6a3.png">

**Comment by piyush-kukadiya** [comment]
@tanveersalmangkn So your saying our example app as well is crashing on start?

**Comment by piyush-kukadiya** [comment]
Also Can you check this out once https://stackoverflow.com/questions/43604603/module-appregistry-is-not-registered-callable-module-calling-runapplication @tanveersalmangkn

**Comment by tanveersalmangkn** [comment]
@piyush-kukadiya 
Nope I'm not talking about the example app, I have implemented the steps as mentioned in example but keeps crashing.

**Comment by piyush-kukadiya** [comment]
@tanveersalmangkn That's what I said earlier, if you can share sample app with me which showcase a crash then I can help you.

**Comment by tanveersalmangkn** [comment]
@piyush-kukadiya 
you want me to share the code or what?

**Comment by tanveersalmangkn** [comment]
@piyush-kukadiya this is AndroidManifest.xml
`
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.app.helwa">

    <uses-permission android:name="android.permission.INTERNET" />

    
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />

    <application
        android:name=".MainApplication"
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:allowBackup="false"
        android:theme="@style/AppTheme">

        <activity
            android:name=".MainActivity"
            android:label="@string/app_name"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
            android:launchMode="singleTask"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="adjustPan">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
                <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
            </intent-filter>
            
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="helwa" />
            </intent-filter>


            
        </activity>
        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />


        
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_name"
                android:value="General"/>
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_channel_description"
                    android:value="General Notifications"/>

        
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                    android:value="false"/>
        
        
        <meta-data  android:name="com.dieam.reactnativepushnotification.channel_create_default"
                    android:value="true"/>
        
        
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                    android:resource="@color/white"/> 

        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
            </intent-filter>
        </receiver>

        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <meta-data android:name="CLEVERTAP_ACCOUNT_ID" android:value="447-KW7-6R6Z" />
        <meta-data android:name="CLEVERTAP_TOKEN" android:value="a03-a44" />
        <meta-data android:name="CLEVERTAP_USE_GOOGLE_AD_ID" android:value="1"/>
        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id" />
    </application>

</manifest>

`

**Comment by tanveersalmangkn** [comment]
@piyush-kukadiya 
MainActivity.java
`
package com.app.helwa;

import android.content.Intent;
import android.os.Bundle;
import android.os.PersistableBundle;

import androidx.annotation.Nullable;

import com.app.helwa.MainApplication;
import com.clevertap.android.sdk.CleverTapAPI;
import com.clevertap.react.CleverTapModule;
import com.facebook.react.ReactActivity;

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "Helwa";
  }

  @Override
  public void onCreate(@Nullable Bundle savedInstanceState, @Nullable PersistableBundle persistentState) {
    CleverTapAPI ct = CleverTapAPI.getDefaultInstance(getApplicationContext());
    super.onCreate(savedInstanceState, persistentState);
    CleverTapModule.setInitialUri(getIntent().getData());
    Intent intent = new Intent(this, MainApplication.class);
    Bundle extras = getIntent().getExtras();
    if(extras !=null){
      intent.putExtras(extras);
    }
    startActivity(intent);
    finish();
  }
}

`

**Comment by tanveersalmangkn** [comment]
@piyush-kukadiya  
this is MainApplication.java

`package com.app.helwa;

import android.app.Application;
import android.content.Context;
import android.os.Handler;
import android.os.Looper;
import android.util.Log;

import com.clevertap.android.sdk.ActivityLifecycleCallback;
import com.clevertap.android.sdk.CleverTapAPI;
import com.clevertap.android.sdk.pushnotification.CTPushNotificationListener;
import com.clevertap.react.CleverTapPackage;
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.bridge.Arguments;
import com.facebook.react.bridge.ReactContext;
import com.facebook.react.bridge.WritableMap;
import com.facebook.react.modules.core.DeviceEventManagerModule;
import com.facebook.reactnative.androidsdk.FBSDKPackage;
import com.microsoft.codepush.react.CodePush;
import com.oblador.vectoricons.VectorIconsPackage;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.soloader.SoLoader;
import com.smartlook.sdk.smartlook.Smartlook;

import org.json.JSONObject;

import java.lang.reflect.InvocationTargetException;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class MainApplication extends Application implements ReactApplication, CTPushNotificationListener {

    private static final String TAG = "MainApplication";

  private final ReactNativeHost mReactNativeHost =
      new ReactNativeHost(this) {

          @Override
          protected String getJSBundleFile() {
              return CodePush.getJSBundleFile();
          }


          @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }


        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
            packages.add(new com.app.helwa.MyAppPackage());
            packages.add(new CleverTapPackage());
          return packages;
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }
      };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
      CleverTapAPI.setDebugLevel(3);
      CleverTapAPI.getDefaultInstance(getApplicationContext()).enableDeviceNetworkInfoReporting(true);
      ActivityLifecycleCallback.register(this);
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
    CleverTapAPI.getDefaultInstance(this)
            .setCTPushNotificationListener(this);
  }

  /**
   * Loads Flipper in React Native templates. Call this in the onCreate method with something like
   * initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
   *
   * @param context
   * @param reactInstanceManager
   */
  private static void initializeFlipper(
      Context context, ReactInstanceManager reactInstanceManager) {
    if (BuildConfig.DEBUG) {
      try {
        /*
         We use reflection here to pick up the class that initializes Flipper,
        since Flipper library is not available in release mode
        */
        Class<?> aClass = Class.forName("com.app.helwa.ReactNativeFlipper");
        aClass
            .getMethod("initializeFlipper", Context.class, ReactInstanceManager.class)
            .invoke(null, context, reactInstanceManager);
      } catch (ClassNotFoundException e) {
        e.printStackTrace();
      } catch (NoSuchMethodException e) {
        e.printStackTrace();
      } catch (IllegalAccessException e) {
        e.printStackTrace();
      } catch (InvocationTargetException e) {
        e.printStackTrace();
      }
    }
  }

    @Override
    public void onNotificationClickedPayloadReceived(HashMap<String, Object> payload) {
        Log.e("MainApplication", "onNotificationClickedPayloadReceived called");
        final String CLEVERTAP_PUSH_NOTIFICATION_CLICKED = "CleverTapPushNotificationClicked";

        Handler handler = new Handler(Looper.getMainLooper());
        handler.post(new Runnable() {
            public void run() {

                // Construct and load our normal React JS code bundle
                final ReactInstanceManager mReactInstanceManager = ((ReactApplication) getApplicationContext())
                        .getReactNativeHost().getReactInstanceManager();
                ReactContext context = mReactInstanceManager.getCurrentReactContext();
                // If it's constructed, send a notification
                if (context != null) {
                    sendEvent(CLEVERTAP_PUSH_NOTIFICATION_CLICKED, getWritableMapFromMap(payload), context);
                } else {
                    // Otherwise wait for construction, then send the notification
                    mReactInstanceManager
                            .addReactInstanceEventListener(new ReactInstanceManager.ReactInstanceEventListener() {
                                public void onReactContextInitialized(ReactContext context) {
                                    sendEvent(CLEVERTAP_PUSH_NOTIFICATION_CLICKED, getWritableMapFromMap(payload),
                                            context);
                                    mReactInstanceManager.removeReactInstanceEventListener(this);
                                }
                            });
                    if (!mReactInstanceManager.hasStartedCreatingInitialContext()) {
                        // Construct it in the background
                        mReactInstanceManager.createReactContextInBackground();
                    }
                }

            }
        });
    }


    private WritableMap getWritableMapFromMap(Map<String, ? extends Object> var1) {
        JSONObject extras = var1 != null ? new JSONObject(var1) : new JSONObject();
        WritableMap extrasParams = Arguments.createMap();
        Iterator extrasKeys = extras.keys();
        while (extrasKeys.hasNext()) {
            String key = null;
            String value = null;
            try {
                key = extrasKeys.next().toString();
                value = extras.get(key).toString();
            } catch (Throwable t) {
                Log.e(TAG, t.getLocalizedMessage());
            }

            if (key != null && value != null) {
                extrasParams.putString(key, value);
            }
        }
        return extrasParams;
    }

    private void sendEvent(String eventName, Object params, ReactContext context) {

        try {
            context.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                    .emit(eventName, params);
        } catch (Throwable t) {
            Log.e(TAG, t.getLocalizedMessage());
        }
    }
}


`

**Comment by tanveersalmangkn** [comment]
@piyush-kukadiya 
Please have a look and let me know

**Comment by tanveersalmangkn** [comment]
@piyush-kukadiya 
After a lot of struggle I was able to solve this issue by removing the `node_modules` and installed via `yarn install`
It worked like a charm.

**Comment by piyush-kukadiya** [comment]
@tanveersalmangkn Above code snippet is not helping me to spot any issue.

1. Create a new sample app project with required CleverTap features
2. This sample app should showcase a crash
3. Commit your project to github and share with me.
4. I will clone and check for crash, will fix it and let you know for any integration related issue.

Hope this clarifies what I am asking for.

**Comment by piyush-kukadiya** [comment]
@tanveersalmangkn That's great. You are awesome!

**Comment by tanveersalmangkn** [comment]
@piyush-kukadiya 
Thanks for the help! Cheers
