### ISSUE TITLE
CleverTap Android v4.3.0 SDK support

### ISSUE THREAD

**Issue by pranshuchittora** [CleverTap/clevertap-react-native#194]
When we can expect v4.3.0 upgrade/support.

<img width="593" alt="Screenshot 2021-11-16 at 4 45 23 PM" src="https://user-images.githubusercontent.com/32242596/141975743-50dcf7db-7900-47da-8a12-df13c5ab1d0f.png">

Good Day

**Comment by darshanclevertap** [comment]
@pranshuchittora CleverTap Android SDK v4.3.0 is live. What is your concern here?

**Comment by pranshuchittora** [comment]
@darshanclevertap React Native SDK is still using v4.2
https://github.com/CleverTap/clevertap-react-native/blob/f388e07c6b8b9555f9295be4e1f395b68d42479d/android/build.gradle#L42

**Comment by darshanclevertap** [comment]
@pranshuchittora Yes, we're currently working on getting the support for Android 12 related changes to our React Native and other hybrid SDKs. I'll provide an ETA for the new React Native SDK with CleverTap Android SDK v4.3.0 changes in a few days.

1. Are there any breaking changes?
A. No breaking changes as such for React Native. All the changes are handled by the Android side.

I hope that answers your question.

**Comment by mohit23x** [comment]
@pranshuchittora the version [0.7.0](https://github.com/CleverTap/clevertap-react-native/releases/tag/0.7.0) now supports android SDK 4.3.1 🎉
