### ISSUE TITLE
Carousel message doesn't work properly on iOS

### ISSUE THREAD

**Issue by vvscode** [CleverTap/clevertap-react-native#196]
`react-native-clevertap: 0.6.0` (started with `0.5.1` and update didn't help)

on Android it looks fine - I see a carousel, I can swipe images and on tap, link is opened

on iOS - I see only first image, no signs that there is something else, tap does nothing

**Comment by Aditi3** [comment]
Can you please confirm if you have installed our [image carousel](https://github.com/CleverTap/CTNotificationContent) and [single media](https://github.com/CleverTap/CTNotificationService) libraries to enable sending Carousel Image for iOS Mobile Push?

You’ll have to integrate our [image carousel](https://github.com/CleverTap/CTNotificationContent) library into your iOS to enable the carousel.

**Comment by Aditi3** [comment]
I'm going to close this issue for now. Feel free to reopen if you have further questions.
