### ISSUE TITLE
Task :clevertap-react-native:compileDebugJavaWithJavac FAILED M1 mac book pro 

### ISSUE THREAD

**Issue by AbdullhRtima** [CleverTap/clevertap-react-native#197]
`Currently detected usages in: root project 'Waseet', project ':app', project ':clevertap-react-native', ...

> Task :app:processDebugManifest

> Task :clevertap-react-native:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
520 actionable tasks: 4 executed, 516 up-to-date
get manifestOutputDirectory error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':clevertap-react-native:compileDebugJavaWithJavac'.
> Could not find tools.jar. Please check that /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 58s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
get manifestOutputDirectory error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by piyush-kukadiya** [comment]
@AbdullhRtima Seems like issue with JDK path, Try setting valid JDK path from Studio. https://stackoverflow.com/questions/19608742/how-to-set-java-sdk-path-in-androidstudio

**Comment by AbdullhRtima** [comment]
@piyush-kukadiya  thanks solved the issue + NDK was missing
