### ISSUE TITLE
Please Mention Detailed Documentation for React native push notification. Using clever tap

### ISSUE THREAD

**Issue by ranvirgorai** [CleverTap/clevertap-react-native#2]

**Comment by pwilkniss** [comment]
@ranvirgorai   please email support at clevertap.com and we'd be happy to help.  closing this issue here.

**Comment by gaelperon** [comment]
Hello,

It would be really nice to have a clear guide to setup push notifications with the React Native SDK.

For now, you have to cherry-pick information in ios and android guide which is very painful and confusing
