### ISSUE TITLE
Support for android sdk v4.4.0

### ISSUE THREAD

**Issue by deepsingh11421** [CleverTap/clevertap-react-native#203]
When can we expect the support for the latest android sdk v4.4.0? @darshanclevertap 

![image](https://user-images.githubusercontent.com/53794402/148028167-83fa331d-357a-4fb9-8f24-c5d9f3dc01fa.png)

**Comment by darshanclevertap** [comment]
@deepsingh11421 CleverTap React Native SDK v0.8.0 has been released which supports CleverTap Android SDK v4.4.0.
Please star/watch this repo to get updates on new releases.
