### ISSUE TITLE
'CleverTapSDK/CleverTap.h' file not found in React Native iOS

### ISSUE THREAD

**Issue by 0xsaranonearth** [CleverTap/clevertap-react-native#209]
I suppose this is a duplicate thread but couldn't get any solution out of the already available threads. 

Getting this `'CleverTapSDK/CleverTap.h' file not found` on React Native iOS when I try to build the app. Would be great if there is a solution.

"clevertap-react-native": "^0.8.0"
"react-native": "0.64.2"

**Comment by akashvercetti** [comment]
@0xsaranonearth We'll try to reproduce this on our end. In the meantime, could you please try running the Example project in the sdk and see if it helps?

**Comment by darshanclevertap** [comment]
@0xsaranonearth We were not able to reproduce this. If you are still facing this issue, please let us know by reopening this issue.
