### ISSUE TITLE
Clevertap failing to record new events

### ISSUE THREAD

**Issue by Md-Mudassir47** [CleverTap/clevertap-react-native#210]
From the past few days, clevertap has stopped recording the new events, the old events are being recorded & shown in the user activity section but the new event isn't being shown. I checked the logs using postman. the event is being sent but on the user's activity screen the event is not being shown.

### Postman request
<img width="402" alt="Screenshot 2022-02-09 at 11 56 19 AM" src="https://user-images.githubusercontent.com/85115578/153134967-74a2bf50-a8d0-4827-a9c4-77efa73fab03.png">

### User Activity screen
<img width="1161" alt="Screenshot 2022-02-09 at 11 59 55 AM" src="https://user-images.githubusercontent.com/85115578/153134666-81cfcb9d-9c1b-4dcb-aa56-7af39cd33f7b.png">

### Version details
` "clevertap-react-native": "^0.7.0",`
`"react-native": "^0.66.3",`

It's failing on both the platforms (iOS, Android)

**Comment by darshanclevertap** [comment]
@Md-Mudassir47 Can you share the Xcode console logs when an event is fired from CleverTap?

**Comment by Md-Mudassir47** [comment]
> Here's the log, it clearly says `Successfully sent 1 events` but doesn't get reflected on user's activity feed.
<img width="740" alt="Screenshot 2022-02-09 at 1 33 04 PM" src="https://user-images.githubusercontent.com/85115578/153149209-5f464ded-7135-418d-820b-e9fd479e9a8c.png">

**Comment by Md-Mudassir47** [comment]
@darshanclevertap any updates on this?

**Comment by darshanclevertap** [comment]
@Md-Mudassir47 Sorry for the delay, are you still facing this issue?

**Comment by Md-Mudassir47** [comment]
> @Md-Mudassir47 Sorry for the delay, are you still facing this issue?

Nope. apparently, there was a limit to the number of events that we can define, and we had exceeded the limit so discarded the unused events, and its working fine now. And please do specify this in your docs about the events limit and try to provide access to unlimited events for the paid users.

**Comment by darshanclevertap** [comment]
@Md-Mudassir47 We have the docs related to [Event constraints here](https://docs.clevertap.com/docs/platform-considerations#general-constraints). We do not provide unlimited events, but if you have a genuine use case to increase the number of events, please reach out to CleverTap Support via the Dashboard.
