### ISSUE TITLE
Push amplification

### ISSUE THREAD

**Issue by shubhamS-vs** [CleverTap/clevertap-react-native#220]
Do we have option to integrate push amplification in react native?
as in the guidelines react native compatibility is not there
![Screenshot 2022-03-22 at 1 49 35 PM](https://user-images.githubusercontent.com/83690733/159446937-a2223e72-0e88-47d0-becd-c575aadf20d4.png)

**Comment by piyush-kukadiya** [comment]
@shubhamS-vs Yes. Please go through [this](https://developer.clevertap.com/docs/android-push#push-amplification)
