### ISSUE TITLE
null is not an object (CleverTapReact)

### ISSUE THREAD

**Issue by ghtjiann4321** [CleverTap/clevertap-react-native#222]
Hi,

I am having this error when requiring the clevertap-react-native in the App.js of our react native application

![Screenshot from 2022-03-24 20-23-13](https://user-images.githubusercontent.com/37067647/159915558-59a75a5f-4794-45de-b507-837a87d652fe.png)

We are using expo and android studio emulator for testing.

```
const CleverTap = require('clevertap-react-native');

export default function App() {
  return (
    <WebView 
      style={styles.container}
      source={{ uri: Constants.manifest.extra.apiUrl }}
      onMessage={handleMessage}
    />
  );
}
```

Additional logs in terminal

```
TypeError: null is not an object (evaluating 'CleverTapReact.CleverTapProfileDidInitialize')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
at node_modules/metro-runtime/src/polyfills/require.js:204:6 in guardedLoadModule
at http://172.20.10.8:19000/node_modules/expo/AppEntry.bundle?platform=android&dev=true&hot=false&strict=false&minify=false:118143:3 in global code

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/@react-native/polyfills/error-guard.js:49:36 in ErrorUtils.reportFatalError
```

**Comment by piyush-kukadiya** [comment]
@ghtjiann4321 I feel it's related to metro server. Please check below.

> This can happen if:
> Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
>  A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.

**Comment by ghtjiann4321** [comment]
We are using Expo and we tried testing it on a different machine but the issue is still the same.

This is how we create the Expo App.
![image (2)](https://user-images.githubusercontent.com/37067647/160806366-4918b96e-dd33-4673-aa7c-e679df73fb19.png)

**Comment by darshanclevertap** [comment]
@ghtjiann4321 Are you using the managed workflow or the Bare workflow on Expo? I'd suggest you eject your Expo app and then try re-installing the CleverTap React Native SDK.

**Comment by ghtjiann4321** [comment]
Will try that thank you for the reply

**Comment by ghtjiann4321** [comment]
[darshanclevertap](https://github.com/darshanclevertap) Thanks for the reply. Unfortunately we are already integrating other services that are compatible and are working with the managed workflow so we cannot eject and refactor every integration we have done. Can you check on the clevertap side what seems to be the error when using the library on the expo application?

**Comment by smn-snkl** [comment]
We are also considering switching back to OneSignal due to the missing Expo support. Is there any other workaround to make it work?

**Comment by darshanclevertap** [comment]
@ghtjiann4321 @smn-snkl Really sorry but we do not have Expo support for the Bare workflow. You will have to eject your app from the Bare Workflow and integrate our React-Native SDK manually for CleverTap to work in your app.
