### ISSUE TITLE
Implicit PendingIntent error from Google Play Store

### ISSUE THREAD

**Issue by yasserwaseet** [CleverTap/clevertap-react-native#224]
Google play with the title Implicit PendingIntent, said Your app contains an Implicit Internal Intent vulnerability.
<img width="824" alt="Screen Shot 2022-04-28 at 1 41 45 AM" src="https://user-images.githubusercontent.com/94108503/165643365-4fe15502-8d26-48a2-9e37-570fac537bc3.png">

**Comment by piyush-kukadiya** [comment]
@yasserwaseet This warning will not affect your app releases.
CleverTap Android SDK v4.3.0 onwards, we started supporting Android 12 and mutability flags to all our Pending Intents. Targeting your app to latest clevertap version and Android 12 will solve this error.

Clevertap Android SDK v4.3.1 is supported by clevertap-react-native [v0.7.0](https://github.com/CleverTap/clevertap-react-native/releases/tag/0.7.0)
