### ISSUE TITLE
How to use Push Template introduced in android sdk 4.4.0

### ISSUE THREAD

**Issue by shubhamdeol** [CleverTap/clevertap-react-native#227]
How to use push templates introduced in latest android sdk with latest version of clevertap-react-native.

What are native side changes required ?

https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTPUSHTEMPLATES.md#template-keys

**Comment by root-ansh-ct** [comment]
Hi, @shubhamdeol .

Support for clevertap push templates for React-native is given from v0.8.1

1. in your package.json class, set `"clevertap-react-native": "^0.8.1"` and run `npm install` 
2. in the `android/app/src/main/java/<your_package_name>/<your_application_class>.java` , add this line before onCreate : `CleverTapAPI.setNotificationHandler((NotificationHandler)new PushTemplateNotificationHandler());`
3. in `android/app/build.gradle` file, add the dependencies `"com.clevertap.android:push-templates:1.0.2"` and `"com.clevertap.android:clevertap-android-sdk:4.4.0"`

You can check the sample [app](https://github.com/CleverTap/clevertap-react-native/tree/master/Example) and [push templates documentation](https://developer.clevertap.com/docs/push-templates-android#installation) for more info.

**Comment by shubhamdeol** [comment]
I do not need to make change in FirebaseMessagingService.java file?
```
CTFcmMessageHandler()
                .createNotification(getApplicationContext(), remoteMessage);
```
