### ISSUE TITLE
Push notification for ios

### ISSUE THREAD

**Issue by khanhkom** [CleverTap/clevertap-react-native#232]
I tried to push notification to ios devices and get this error "No registration IDs/Profiles specified". I had add .p12 for push notifitaion, when i check profile in clever tap ios is Not Reachable.

**Comment by akashvercetti** [comment]
Hi @khanhkom , Could you please show us how are you setting up push notifications in the app? Also, could you double check your code with this [documentation](https://developer.clevertap.com/docs/react-native-push-notification#ios) ?
