### ISSUE TITLE
Push notification on android not working!

### ISSUE THREAD

**Issue by khanhkom** [CleverTap/clevertap-react-native#238]
I am using Xiaomi and config all clevertap mobile push. I am using FCM to push notification on android. I test push notification to device by find user on dashboard but i can't receipt any notification in my device. But, i get FCM token from Clevertap and using it to send notification in https://testfcm.com, it working well.

**Comment by william-ct** [comment]
Hey @khanhkom While configuring FCM with CleverTap, did you add/create notification channel for you app? Also have you setup FCM credentials on your CleverTap dashboard?

**Comment by khanhkom** [comment]
Yes, i had create channel notification in my app by using function: createNotificationChannel. i checke the chennel was created. And i also setup FCM credentials by add Sender ID and Server key get from firebase console. But i can not show this credential in Clevertap to check it because it alway show ***.

**Comment by khanhkom** [comment]
![image](https://user-images.githubusercontent.com/44663895/175493583-ff52472f-9d28-4437-8b9e-4892b56f5aa0.png)

**Comment by khanhkom** [comment]
![image](https://user-images.githubusercontent.com/44663895/175493638-67580391-b206-4895-8657-f69f104a1076.png)

**Comment by khanhkom** [comment]
Results is success but i can not receipt any notification on my real device (xiaomi redmi 9T)

**Comment by khanhkom** [comment]
![image](https://user-images.githubusercontent.com/44663895/175500532-2392646a-3ecb-488f-bf0b-4087f405f0b5.png)
 I fogot setup this line. After add this to AndroidManifest.xml, notification work okela.
