### ISSUE TITLE
Custom event getting triggered in before identity being set for the user profile

### ISSUE THREAD

**Issue by Cshayan** [CleverTap/clevertap-react-native#239]
Hi,

In our app, when user logs in we set the idenity of the user in clevertap with an unique identifier and after that we trigger a custom event for that login event. But in clevertap dashboard for the user profiles we are seeing - that custom event getting triggered first and then identity of the user being set.

Is there a way I can get to know the identity has been set and then propbably trigger that custom event?

Platform - 
React Native
Version - 
"clevertap-react-native": "0.8.1"

Thanks.

**Comment by Cshayan** [comment]
hi @darshanclevertap can you please look into this?

**Comment by william-ct** [comment]
Hi @Cshayan Currently in our SDK, we do not provide any callbacks for `onUserLogin()` and setting the Identity of the user is a backend driven event. So right now you can't trigger a custom event based on Identity Set
