### ISSUE TITLE
Mobile in App android not showing

### ISSUE THREAD

**Issue by HyuArzani** [CleverTap/clevertap-react-native#24]
Hello i want to user mobile in app message in android, in ios it was showed after i trigger clevertap event, how to show the in app message in android?

**Comment by darshanclevertap** [comment]
Hi @HyuArzani Could you please give us more details (logs/screenshots) on what did not work specifically? Like, which type of inapp message were you trying to send? Did you see some logs which had shown some errors? Have you integrated the clevertap-react-native correctly for Android? This will help us to solve your issue in a swift manner.
Thanks

**Comment by darshanclevertap** [comment]
Have you followed the [Install instructions](https://github.com/CleverTap/clevertap-react-native/blob/master/docs/install.md) and [Integration steps](https://github.com/CleverTap/clevertap-react-native/blob/master/docs/integration.md) mentioned in the [README](https://github.com/CleverTap/clevertap-react-native/blob/master/README.md)?

**Comment by HyuArzani** [comment]
of course, no error when i log on android studio, this is my capture:

<img width="1170" alt="screen shot 2018-11-16 at 16 41 02" src="https://user-images.githubusercontent.com/27977978/48613527-9359e400-e9be-11e8-9dcf-b16b56b1a0ec.png">

this is my campaign setting target:

<img width="1071" alt="screen shot 2018-11-16 at 16 42 41" src="https://user-images.githubusercontent.com/27977978/48613579-bd130b00-e9be-11e8-86d3-fdefb9776863.png">

there's no message received log on my log cat after the event queu sent, is it expected behaviour?
i use android 8.1.0 to test, is it because blocked because no channelID? but no error happened on my log, i've follow example android manifest:

<img width="712" alt="screen shot 2018-11-16 at 16 45 53" src="https://user-images.githubusercontent.com/27977978/48613735-2135cf00-e9bf-11e8-9c0b-60637647671d.png">

in ios the in app pop up was fine and executed, is there i miss something to received in app in android

**Comment by HyuArzani** [comment]
the thing is, normal push campaign was fine in android, but in app are not working

**Comment by darshanclevertap** [comment]
@HyuArzani Thank you so much for the details. First, by looking at the console logs, I can see that you're using the clevertap-react-native plugin v0.2.5. I would recommend you to update to [v0.2.6](https://www.npmjs.com/package/clevertap-react-native). Meanwhile, I believe this might be an issue with the back end so I will also pass on all these details and get back to you as soon as possible.

**Comment by Aditi3** [comment]
Closing it due to inactivity, if you are still facing the issue reach out to us at support@clevertap.com.

Thanks!
