### ISSUE TITLE
'CleverTap.h' file not found

### ISSUE THREAD

**Issue by CatWithNineLives** [CleverTap/clevertap-react-native#243]
I am implementing iOS push impressions for my react native app with CleverTap already integrated.
Using this [guide](https://developer.clevertap.com/docs/push-notifications-ios#push-impressions)
I have added a Notification Service Extension.
But getting the following error in the ```NotificationService.m``` file :
```'CleverTap.h' file not found```
for the line ```#import <CleverTap.h>```

<img width="642" alt="Screenshot 2022-08-05 at 4 15 39 PM" src="https://user-images.githubusercontent.com/25013452/183061738-70adcd00-39a9-423d-bd17-0f8dc80b1da6.png">

<img width="383" alt="Screenshot 2022-08-05 at 4 27 40 PM" src="https://user-images.githubusercontent.com/25013452/183063661-5a15a4f9-88ce-4090-a369-92631d45ea42.png">

clevertap-react-native = 0.8.1 
CleverTap-iOS-SDK = 4.0.0

Since CleverTap was already integrated before, this import line is working perfectly in the ```AppDelegate.m``` file.

**Comment by akashvercetti** [comment]
@CatWithNineLives Notification Extensions run independently from the parent/base app, as in we would need to add dependencies for them separately. So could you try adding one of the two snippets below to your ios app Podfile?

`target 'NotificationService' do
     pod 'CleverTap-iOS-SDK'
  end`

OR

`target 'NotificationService' do
    inherit! :search_paths
  end`

**Comment by CatWithNineLives** [comment]
> @CatWithNineLives Notification Extensions run independently from the parent/base app, as in we would need to add dependencies for them separately. So could you try adding one of the two snippets below to your ios app Podfile?
> 
> `target 'NotificationService' do pod 'CleverTap-iOS-SDK' end`
> 
> OR
> 
> `target 'NotificationService' do inherit! :search_paths end`

This works, thanks for the help! Makes sense in retrospect.
