### ISSUE TITLE
getProductConfigString returning empty

### ISSUE THREAD

**Issue by Felipelpk** [CleverTap/clevertap-react-native#245]
Hi guys,

I'm creating an A/B test for a banner in my app but I'm not able to get it to return the correct value of my key within my app it always returns empty.

```
CleverTap.getProductConfigString('subscriptionBanner', (error, res) => {
  if (error) return console.log(error.message);
  console.log(res, "<- Subscription Banner Url")
});
```

**output:**

<img width="425" alt="Screen Shot 2022-08-10 at 14 27 13" src="https://user-images.githubusercontent.com/44594611/183977633-f0fa502c-c101-4d72-aaa1-a765be555fc1.png">

**Comment by darshanclevertap** [comment]
@Felipelpk Are you calling the `fetchAndActivate` method before calling `getProductConfigString` method?

**Comment by Felipelpk** [comment]
@darshanclevertap yes

**Comment by darshanclevertap** [comment]
@Felipelpk I'd suggest you reach out to our support team here. We would need to see the campaign you have created on the dashboard and the values set for the keys as well to understand this better. Please do share a debug APK with them as well.

You can create a support ticket by clicking on "Need Help?" on the top right of the dashboard and then clicking on "Create a Support ticket"

Thanks!
