### ISSUE TITLE
Push Notifications - Using @react-native-firebase/messaging for generating FCM Token 

### ISSUE THREAD

**Issue by smohit02** [CleverTap/clevertap-react-native#246]
My requirement is to get the FCM token only from [@react-native-firebase/messaging](https://rnfirebase.io/messaging/usage).

And send this token to Clevertap using CleverTap.setPushToken() without having to write Native Java Code for generating token from the FirebaseMessagingService class.

This is, since I want to receive notifications from the Firebase Console as well as Clevertap Dashboard using the token generated from "messaging().getToken()" from the @react-native-firebase/messaging, as I can control this from my React Native code.

I don't understand why is there a need for the Native FirebaseMessagingService class and all the native code in the MainApplication.java.
If someone can please elaborate on this, and what exactly is custom notification handling?

**Comment by piyush-kukadiya** [comment]
@smohit02 Please share a document that you are following. It's optional to have `FirebaseMessagingService` class if you are using your own fcm implementation or any other provider's implementation.

**Comment by smohit02** [comment]
I am following the official Clevertap React Native Push Docs along with https://rnfirebase.io/messaging/usage for getting FCM token.

My only concern now is that if the user deletes the app, and re installs it, Clevertap Dashboard Profile of that user does not record new data and the new FCM token if generated, does not registered on Clevertap.

How can we handle this case, where a new FCM token for an existing user needs to be updated on Clevertap.

**Comment by piyush-kukadiya** [comment]
@smohit02 You can pass new token to dashboard whenever you want,  with same method https://github.com/CleverTap/clevertap-react-native/blob/master/docs/usage.md#registering-fcm-token 

If you are facing integration related issues, please reach out to our support team.
