### ISSUE TITLE
Clevertap events during development mode

### ISSUE THREAD

**Issue by shubhnik** [CleverTap/clevertap-react-native#25]
All the Clevertap events are pushed even in dev mode. I just want to see production events on my Clevertap dashboard. Is it possible to setup different keys for dev mode so that dev events don't pollute the production events?

**Comment by Aditi3** [comment]
Hey @shubhnik 

I would recommend using CleverTap Test Account credentials for development mode and update the credentials once you want to push the data to Production mode with the CleverTap account credentials.

To implement the same, in android, navigate to the AndroidManifest.xml file in your project navigator and add your CleverTap Account ID and Token to your AndroidManifest.xml, within the <application></application> tags. 

In iOS, Navigate to the Info.plist file in your project navigator and add the CleverTapAccountID and CleverTapToken key with the values.

**Comment by shubhnik** [comment]
Thanks, @Aditi3  . I have created a test account and change the credentials based on dev/prod mode.
