### ISSUE TITLE
No resource identifier found for attribute 'appComponentFactory' in package 'android'.

### ISSUE THREAD

**Issue by PaliwalSparsh** [CleverTap/clevertap-react-native#27]
Hi,
I followed all the instructions for integrating clevertap but i am getting this error -

```
/Users/sparshpaliwal/Desktop/docstat-native/android/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:43: AAPT: No resource identifier found for attribute 'appComponentFactory' in package 'android'


FAILURE: Build failed with an exception.
```

I tried to debug the issue and look for solutions but most of the solutions didnt seem to be working for me. It is something related to updating dependecies to androidx.

We are using `"react-native": "^0.57.0"`. Please let me know if you need more information.

**Comment by darshanclevertap** [comment]
Hi @PaliwalSparsh 

Can you tell me which version of the Android support libraries are you using in your app ?

**Comment by darshanclevertap** [comment]
@PaliwalSparsh Were you able to fix this? This thread has been inactive since long. I'm closing this. If you have any questions you can reach out to our support team on support@clevertap.com
