### ISSUE TITLE
incorrect type definitions

### ISSUE THREAD

**Issue by LonelyCpp** [CleverTap/clevertap-react-native#273]
## missing types
types for these exported constants are missing in `index.d.ts`
```
FCM: CleverTapReact.FCM,
XPS: CleverTapReact.XPS,
BPS: CleverTapReact.BPS,
HPS: CleverTapReact.HPS,
```

## incorrect types
both `profileGetCleverTapAttributionIdentifier` and `profileGetCleverTapID` have incorrect callback types.

index.d.ts says they both get a callback with res as an "object", but both get "string" in their callbacks

---

please add a `@deprecated`  tag in the comments rather than just saying "this is deprecated". IDEs actually warn users when it sees this tag

**Comment by piyush-kukadiya** [comment]
@LonelyCpp Thanks for feedback.  This will get fixed in next release.
