### ISSUE TITLE
Possible Vulnerability

### ISSUE THREAD

**Issue by umar98** [CleverTap/clevertap-react-native#274]
Greetings,

So, while conducting our VAPT assessment I came across an issue that as per our regularity we're not allowed to install hardcoded credentials in the Manifest or Info.plist file. Any workaround for this method?

**Comment by piyush-kukadiya** [comment]
@umar98 You can go through this https://github.com/CleverTap/clevertap-react-native/blob/master/index.js#L204

**Comment by umar98** [comment]
> @umar98 You can go through this https://developer.clevertap.com/docs/android-advanced-features#changing-account-credentials

Thank You. Any such this for the React Native SDK? If not, can also such be found for IOS?

**Comment by piyush-kukadiya** [comment]
@umar98 Api is not there for React native Android, you will have to use native code. @akashvercetti Can you comment on iOS?

**Comment by akashvercetti** [comment]
@umar98 you can try this: https://developer.clevertap.com/docs/advanced-options-ios#setting-account-credentials

**Comment by umar98** [comment]
@piyush-kukadiya, @akashvercetti  Thank you for all your efforts.

Is there any way around I can avoid this in React Native? I use React Native build as per our Compliant Body, we're not allowed to have any data in the Manifest or the list file.

**Comment by darshanclevertap** [comment]
@umar98 Were you able to run this for React Native?
