### ISSUE TITLE
SDWebImage compatibility

### ISSUE THREAD

**Issue by LukasMod** [CleverTap/clevertap-react-native#278]
Hi, 
there is compatibility issue with react-native-fast-image.
Please update clevertap-react-native to use the last version of SDWebImage

```

CocoaPods could not find compatible versions for pod "SDWebImage":
  In Podfile:
    RNFastImage (from `../node_modules/react-native-fast-image`) was resolved to 8.6.3, which depends on
      SDWebImage (~> 5.11.1)

    clevertap-react-native (from `../node_modules/clevertap-react-native`) was resolved to 0.9.3, which depends on
      CleverTap-iOS-SDK (= 4.1.2) was resolved to 4.1.2, which depends on
        SDWebImage (~> 5.1)
```

**Comment by akashvercetti** [comment]
@LukasMod Noted. We will be updating this dependency issue in the next release 👍

**Comment by LukasMod** [comment]
Great! Thanks for super fast answer. Can you share when to expect the new version?

**Comment by LukasMod** [comment]
I did that, and also tried rm node_module and reinstall. But sadly didn't work.

**Comment by akashvercetti** [comment]
@LukasMod we have updated dependencies in our latest release v0.9.4. Could you please try updating and check if it helps?

**Comment by LukasMod** [comment]
Yup, it helped. Thank you

```
   "react-native": "0.69.7",
    "clevertap-react-native": "0.9.4",
    "react-native-fast-image": "8.6.3",
```
