### ISSUE TITLE
React Native Proguard Config Docs

### ISSUE THREAD

**Issue by smgrv123** [CleverTap/clevertap-react-native#279]
Documentation for proguard rules not found in documentation.

**Comment by darshanclevertap** [comment]
@smgrv123 The Android SDK shipped with the React Native SDK has the [Proguard rules inbuilt](https://github.com/CleverTap/clevertap-android-sdk/blob/master/clevertap-core/consumer-rules.pro).

Can you please let us what exactly you are trying to control with the Proguard rules?
