### ISSUE TITLE
minSDK upgrade to 21

### ISSUE THREAD

**Issue by saczx** [CleverTap/clevertap-react-native#280]
Hi, could you please upgrade the min SDK on Android to 21 ? Otherwise it wouldn't compile in usage with other tools like detox

Why the minSDK is set to 16 ? In the latest react-native version the minSDK is set to 21, it could lead to many issues

Thanks in advance,

**Comment by darshanclevertap** [comment]
@saczx Our React Native SDK is a wrapper over Android SDK, our Android SDK min support is currently 19. We do have clients who need support till v19 and hence we cannot upgrade to v21.
