### ISSUE TITLE
Support RN new architecture 

### ISSUE THREAD

**Issue by shubhamdeol** [CleverTap/clevertap-react-native#286]
This is an issue requesting support for Turbo Module architecture. 
Let me know how can we get started. I am open to contribute.

**Comment by darshanclevertap** [comment]
@shubhamdeol Could you let us know why the current architecture is not suited to your needs?

**Comment by shubhamdeol** [comment]
React Native community is migrating to new architecture it has some benefits like improved performance and start up time and much more. 
To be on new architecture it is required that all the dependencies must support new architecture. 
Following is the list of libraries has support for new RN architecture.  

Suppose in future we plan to migrate to new Architecture as well. CleverTap dependency can be blocker for us. So I just want to confirm if you have any plans to support new architure near future. 

https://github.com/reactwg/react-native-new-architecture/discussions/categories/libraries

**Comment by darshanclevertap** [comment]
@shubhamdeol We try and keep our SDK up to date with the new features of React Native. So, we will be doing our research on this.

> To be on new architecture it is required that all the dependencies must support the new architecture.

The biggest problem I see with this is backward compatibility. If we migrate our SDK to the new architecture, all our clients may or may not be able to use it. And it is very difficult to maintain 2 versions of the SDK.

Having said that, we will research this internally and decide whether it makes sense for us to migrate to the new architecture at this point in time.

I will keep this thread open and will respond as soon as we have more information

**Comment by shubhamdeol** [comment]
okay. You will get a flag if user is on new Architecture or not. 
Most libraries are adding support for new architecture using that flag. You won't need to have 2 versions. In single version you can maintain the code using that flag. 
Currently very few forks are on new architecture. Soon this might become the business requirement for you as well.

**Comment by maulik54e** [comment]
any updates on this ..?
when it will be out ..? really need this

**Comment by darshanclevertap** [comment]
@maulik54e This is on our roadmap for the current quarter. I will provide you an update as soon as we have something

**Comment by ajeetfancode** [comment]
@darshanclevertap Any further update on this?

**Comment by darshanclevertap** [comment]
@nickvgn 

Yes, this has been prioritized by our team. We have started initial research on how we can adopt the new RN architecture without breaking anything from a backward compatibility POV. However, at this time, I won't be able to give you an ETA on this. I need to discuss this internally and I will provide an ETA by next week.

The Google Sheet shared by you is quite helpful to see how other libraries are adopting this new architecture. Can we know who is maintaining this sheet? We would want CleverTap to be added there so that developers know the status and eventual ETA for the new RN architecture changes.

**Comment by nickvgn** [comment]
@darshanclevertap Thank you for your prompt response and for taking this seriously. I'm not sure who is maintaining the architecture support spreadsheet but this is where the [discussion](https://github.com/reactwg/react-native-new-architecture/discussions/167) is taking place. There are plenty of resources there as well others other library authors trying to do the same. Hope that helped. Excited to see some updates on this soon.

**Comment by ayushnathani** [comment]
@darshanclevertap Do we have any update on this? We are trying to enable new architecture in our app and this is a blocker for us

**Comment by udasi-jew-peter** [comment]
Same here, we are also looking to enable New Architecture but are stuck since CleverTap doesn't support New Architecture yet :(

**Comment by shubhamdeol** [comment]
React native came up with interop layer through which libraries using older architecture would work. 

But this is temporary they will remove the layer soon

**Comment by Anush-Shand** [comment]
Support for RN new architecture has been added in v3.0.0
NPM link : https://www.npmjs.com/package/clevertap-react-native/v/3.0.0
Changelog : https://github.com/CleverTap/clevertap-react-native/blob/master/CHANGELOG.md#version-300-8-october-2024
