### ISSUE TITLE
Support Notification runtime permission on Android

### ISSUE THREAD

**Issue by manikandanbaskara** [CleverTap/clevertap-react-native#287]
Hi Team,

RN : 0.67.5
clevertap-react-native: 0.8.0

React native library is not supporting the Runtime permissions for push notifications yet as of [Release 0.9.4](https://github.com/CleverTap/clevertap-react-native/releases/tag/0.9.4).

[clevertap-android-sdk](https://github.com/CleverTap/clevertap-android-sdk) started supporting on [Version 4.7.0](https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTCORECHANGELOG.md#version-470-november-1-2022)

I wonder if there any timeline for adding this capability

**Comment by piyush-kukadiya** [comment]
@manikandanbaskara ETA 1st week of JAN 2023.

**Comment by manikandanbaskara** [comment]
Thank you very much. Looking forward 🥂

**Comment by shivamsharma2710** [comment]
Hi @manikandanbaskara

We've added the support for this in our recent [React Native release v1.0.0](https://github.com/CleverTap/clevertap-react-native/releases/tag/1.0.0). For the integration changes, refer the [documentation](https://developer.clevertap.com/docs/react-native-push-notification#push-notifications-permission).
