### ISSUE TITLE
Clevertap.profileSet not working

### ISSUE THREAD

**Issue by shreyaMehndiratta** [CleverTap/clevertap-react-native#288]
User Profile is created on Clevertap but Not able to opt in to whatsapp push using following code:

CleverTap.profileSet({'MSG-whatsapp': true})
OR
CleverTap.onUserLogin({'MSG-whatsapp': true})

Neither of the above is updating the profile, Communication Preferences still shows as Whatsapp Unsubscribed

React native version: 0.67.3
Clevertap-react-native: 0.9.4

**Comment by Amitkumarttn** [comment]
Hi Shrey, Thanks for this?
I am also looking for the same solution
