### ISSUE TITLE
CocoaPods could not find compatible versions for pod "CleverTap-iOS-SDK"

### ISSUE THREAD

**Issue by edgaralfaro123** [CleverTap/clevertap-react-native#291]
[!] CocoaPods could not find compatible versions for pod "CleverTap-iOS-SDK":
  In Podfile:
    clevertap-react-native (from `../node_modules/clevertap-react-native`) was resolved to 0.9.4, which depends on
      CleverTap-iOS-SDK (= 4.1.5)

    rudder-integration-clevertap-react-native (from `../node_modules/@rudderstack/rudder-integration-clevertap-react-native`) was resolved to 1.0.3, which depends on
      CleverTap-iOS-SDK

Specs satisfying the `CleverTap-iOS-SDK, CleverTap-iOS-SDK (= 4.1.5)` dependency were found, but they required a higher minimum deployment target.

react-native: 0.63.3

**Comment by evelant** [comment]
It looks like maybe they pulled version 4.1.5 but didn't realize that the react-native library depends upon it? @kushagraa14 @piyush-kukadiya @nzagorchev we can't build our apps on iOS due to this. Please fix it ASAP.

**Comment by evelant** [comment]
Hmm or maybe a cocoapods issue? `pod search CleverTap-iOS-SDK` shows:

```
-> CleverTap-iOS-SDK (4.2.0)
   The CleverTap iOS SDK for App Analytics and Engagement.
   pod 'CleverTap-iOS-SDK', '~> 4.2.0'
   - Homepage: https://github.com/CleverTap/clevertap-ios-sdk
   - Source:   https://github.com/CleverTap/clevertap-ios-sdk.git
   - Versions: 4.2.0, 4.1.6, 4.1.5, 4.1.4, 4.1.3, 4.1.2, 4.1.1, 4.1.0, 4.0.1, 4.0.0, 3.10.0, 3.9.4, 3.9.3, 3.9.2, 3.9.1, 3.9.0, 3.8.2, 3.8.1, 3.8.0, 3.7.3, 3.7.2, 3.7.1, 3.7.0, 3.6.0, 3.5.0, 3.4.2, 3.4.1, 3.4.0, 3.3.0, 3.2.2, 3.2.1, 3.2.0, 3.1.7, 3.1.6, 3.1.5, 3.1.4, 3.1.3, 3.1.2, 3.1.1, 3.1.0, 3.0.0, 2.2.2, 2.2.1,
   2.2.0, 2.1.2, 2.1.1, 2.1.0, 2.0.10, 2.0.9, 2.0.8, 2.0.7, 2.0.6, 2.0.5, 2.0.4, 2.0.2, 2.0.1, 1.83.34 [trunk repo]
```

4.1.5 is definitely listed there, so why can't it be resolved?

**Comment by edgaralfaro123** [comment]
this is my version cocoapods 1.11.3 but i don't have idea, why show this error?

**Comment by evelant** [comment]
As a test I created an empty app with xcode, added cocoapods, and added `pod "CleverTap-iOS-SDK","'=4.1.5"` to the podfile. That installs without issue. For some reason however, my react-native app says it cannot find the pod.

I didn't change anything in my app when this started failing, I'm not sure what could be going wrong.

**Comment by evelant** [comment]
@edgaralfaro123 I believe I found the issue and it was in my code. I had a custom expo plugin that wrote `pod "CleverTap-iOS-SDK", modular_headers: true` to my Podfile (for compatibility with `use_frameworks!` due to google sdks from react-native-firebase I have to use modular_headers). This used to work just fine, but for whatever reason it no longer works. To make it work I had to add the explicit version to my Podfile, as in `pod 'CleverTap-iOS-SDK', '4.1.5', modular_headers: true`. After doing that the pod installed successfully.

I've got a couple other pods showing similar behavior however. I don't know what might have changed to cause this new failure to resolve versions.

**Comment by kushagraa14** [comment]
Hi @edgaralfaro123 
Have you followed the steps:

- Remove `podfile.lock` from your project.
- Install the dependency once again with `pod install --repo-update`
If not, can you please try out these steps? 
Also can you please let me know what is your minimum deployment target? We support from iOS 10.0 so if your deployment target is lower than that it will cause an issue.
