### ISSUE TITLE
Showing error while build ios app 'CleverTapSDK/CleverTap.h' file not found and 'CleverTapReact/CleverTapReactManager.h' file not found

### ISSUE THREAD

**Issue by tanviagarwaltravel** [CleverTap/clevertap-react-native#30]
Installed npm install -s  clevertap-react-native

Installed pod ->   pod 'CleverTap-iOS-SDK'

Still showing error.

**Comment by Aditi3** [comment]
Hey @tanviagarwaltravel 

Could you please try including the **use_frameworks!** in your podfile.

CleverTapSDK is a dynamic framework, by specifying **use_frameworks!** you can make CocoaPods integrate to your project via frameworks instead of static libraries. Therefore I suggest try including use_framework! in the pod file and then build your project.

**Comment by tanviagarwaltravel** [comment]
Thanks Aditi. Just want to know can we receive push notifications from CleverTap in react-native? If yes, can you share some code snippet?

**Comment by Aditi3** [comment]
Glad it worked for you. 

Yes, you can receive push notifications from CleverTap.

To implement push notifications in iOS React Native, please check included ExampleProject.js: https://github.com/CleverTap/clevertap-react-native/blob/master/ExampleProject/ExampleProject.js

Here you can see, by calling the below method:

// for iOS only: register for push notifications CleverTap.registerForPush();

you can enable support for push notifications.

**Comment by Aditi3** [comment]
Hope this helps.

Closing it, if you need further help you can also write to support@clevertap.com or you can post on https://community.clevertap.com/

Thanks!

**Comment by shrmaky** [comment]
I was integrating in React Native `0.65`

In Podfile -

pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native', modular_headers: true
pod 'CleverTap-iOS-SDK', modular_headers: true

In AppDelegate.m, changed to -
```
#import <CleverTap-iOS-SDK/CleverTap.h>
#import <clevertap-react-native/CleverTapReactManager.h>
```

I am able to build now.

cc @Aditi3

**Comment by dilipyadav98** [comment]
<img width="1680" alt="Screenshot 2024-09-06 at 2 06 49 AM" src="https://github.com/user-attachments/assets/1dd6e411-40cc-468a-b3f9-c177a46f9a31">
<img width="1649" alt="Screenshot 2024-09-06 at 2 09 12 AM" src="https://github.com/user-attachments/assets/cb158093-f8c6-485d-9e24-13736b1a5ae3">


I am use pod for 
  pod "CleverTap-iOS-SDK"
  and use package for CTNotificationService
I getting this issue please check my screen short

**Comment by gyanupadhyay** [comment]
@Aditi3 Any update on the above issue I am also facing the same issue?
