### ISSUE TITLE
minSdk issue

### ISSUE THREAD

**Issue by mushtaque87** [CleverTap/clevertap-react-native#300]
Get this error on trying to create android Test  build for Detox 

`./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug`

_Execution failed for task ':clevertap-react-native:processDebugAndroidTestManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [com.facebook.react:react-native:0.70.7] /Users/mushtaqueahmed/.gradle/caches/transforms-3/bbb4e4848a6502ebfaadd5923c90dcbf/transformed/jetified-react-native-0.70.7-debug/AndroidManifest.xml as the library might be using APIs not available in 19
        Suggestion: use a compatible library with a minSdk of at most 19,
                or increase this project's minSdk version to at least 21,
                or use tools:overrideLibrary="com.facebook.react" to force usage (may lead to runtime failures)_

**Comment by darshanclevertap** [comment]
@mushtaque87 Is this happening for only RN v0.70.7? or for lower versions for React Native as well?
Also, can you try out the answer mentioned on this SO link -> https://stackoverflow.com/a/71169851

**Comment by darshanclevertap** [comment]
@mushtaque87 Is this still happening? If yes, feel free to reopen the ticket with relevant information. Thanks!
