### ISSUE TITLE
Clicking on notification not calling any CleverTap method in react-native

### ISSUE THREAD

**Issue by tanviagarwaltravel** [CleverTap/clevertap-react-native#31]

**Comment by Aditi3** [comment]
Hey @tanviagarwaltravel 

Seems like you want to handle the push notifications payload and process the user's response to a notification.

Here is the link where you can find the answer for both the platform iOS and Android to handle the notifications: https://stackoverflow.com/questions/55350391/cannot-read-payload-of-push-notification-sent-from-clevertap-dashboard/55361276#55361276

Hope this helps.

**Comment by Aditi3** [comment]
Hope this helps.

Closing it, if you need further help you can also write to support@clevertap.com or you can post on https://community.clevertap.com/

Thanks!

**Comment by gaston-munoz** [comment]
@Aditi3  

There is no solution for React Native, a way to add an event listener or subscriber ??
The solution is only native ??

**Comment by Aditi3** [comment]
Hi @gaston-munoz If you want to read the custom extras key-value pairs passed in CleverTap Push Notification Campaigns, then you can implement `CleverTapPushNotificationClicked` event listener.

[Here's the reference code]( https://github.com/CleverTap/clevertap-react-native/blob/master/Starter/App.js#L68).

**Comment by gaston-munoz** [comment]
Hello @Aditi3, good, thanks for that.

Exists one solution for suscriber click notification when the app is closed??
I need read the customs pairs key-value and in my tests not call the listeners

Other, exists subcriber to clicked in-app notificatio s??

**Comment by Aditi3** [comment]
@gaston-munoz For push notifications, launched from the killed state you need to implement the following piece of code, the reason being when the app starts from the killed state, React Native takes some time to initialize the JS Core. Due to this the push notification click callback fired by OS is missed in RN. The callback is fired earlier than RN listeners get set up.

In your `AppDelegate.m` file, under `didFinishLaunchingWithOptions` method pass `launchOptions` with initial properties as below

```
RCTRootView *rootView [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"ReactNativeExampleiOS"
                                            initialProperties:launchOptions];
```
Now in the App.js file under App class, please make changes as below

```
class App extends React.Component {

  constructor(props){
      super(props);
      console.log('initial props:', props);
      if(props.UIApplicationLaunchOptionsRemoteNotificationKey){
    	 Alert.alert(JSON.stringify(props.UIApplicationLaunchOptionsRemoteNotificationKey)); // here you can get the payload 
      }
   }
}
```

**Comment by gaston-munoz** [comment]
@Aditi3 

Ok, thanks,  I'm going to try, is there a similar solution for Android?

**Comment by piyush-kukadiya** [comment]
@gaston-munoz If i get your question correctly then you can try this out https://github.com/CleverTap/clevertap-react-native/commit/be647bab97081bbec8d8a8d7faaaa944bf4a877f for `Android`

**Comment by gaston-munoz** [comment]
@Aditi3 Thanks, works in ios!!

Testing the `android` solution proposed by @piyush-kukadiya

**Comment by gaston-munoz** [comment]
Hello @piyush-kukadiya!

I am not a specialist in native code, do you have that solution for kotlin?

**Comment by gaston-munoz** [comment]
> @gaston-munoz If i get your question correctly then you can try this out [be647ba](https://github.com/CleverTap/clevertap-react-native/commit/be647bab97081bbec8d8a8d7faaaa944bf4a877f) for `Android`

Maybe you can refer me to some resource to get the solution in Kotlin?

**Comment by piyush-kukadiya** [comment]
@gaston-munoz Try this out (in **Kotlin**):

```

package com.starter

import android.os.Handler
import android.os.Looper
import android.util.Log
import androidx.multidex.MultiDexApplication
import com.clevertap.android.sdk.ActivityLifecycleCallback
import com.clevertap.android.sdk.CleverTapAPI
import com.clevertap.android.sdk.pushnotification.CTPushNotificationListener
import com.clevertap.react.CleverTapPackage
import com.facebook.react.ReactApplication
import com.facebook.react.ReactInstanceManager.ReactInstanceEventListener
import com.facebook.react.ReactNativeHost
import com.facebook.react.ReactPackage
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.ReactContext
import com.facebook.react.bridge.WritableMap
import com.facebook.react.modules.core.DeviceEventManagerModule.RCTDeviceEventEmitter
import com.facebook.react.shell.MainReactPackage
import com.facebook.soloader.SoLoader
import java.util.HashMap

class MainApplication1 : MultiDexApplication(), ReactApplication, CTPushNotificationListener {

    private val TAG = "MainApplication"
    private val mReactNativeHost: ReactNativeHost = object : ReactNativeHost(this) {
        override fun getUseDeveloperSupport(): Boolean {
            return BuildConfig.DEBUG
        }

        override fun getPackages(): List<ReactPackage> {
            return listOf(
                MainReactPackage(),
                CleverTapPackage()
            )
        }

        override fun getJSMainModuleName(): String {
            return "index"
        }
    }

    override fun getReactNativeHost(): ReactNativeHost {
        return mReactNativeHost
    }

    override fun onCreate() {
        ActivityLifecycleCallback.register(this)
        super.onCreate()
        SoLoader.init(this,  /* native exopackage */false)
        CleverTapAPI.getDefaultInstance(this)?.ctPushNotificationListener = this
    }

    //Push Notification Clicked callback
    override fun onNotificationClickedPayloadReceived(payload: HashMap<String, Any>) {
        Log.e("MainApplication", "onNotificationClickedPayloadReceived called")
        val CLEVERTAP_PUSH_NOTIFICATION_CLICKED = "CleverTapPushNotificationClicked"
        val handler = Handler(Looper.getMainLooper())
        handler.post {
            // Construct and load our normal React JS code bundle
            val mReactInstanceManager = (applicationContext as ReactApplication).reactNativeHost.reactInstanceManager
            val context = mReactInstanceManager.currentReactContext
            // If it's constructed, send a notification
            if (context != null) {
                sendEvent(CLEVERTAP_PUSH_NOTIFICATION_CLICKED, payload.toWritableMap(), context)
            } else {
                // Otherwise wait for construction, then send the notification
                mReactInstanceManager.addReactInstanceEventListener(object : ReactInstanceEventListener {
                    override fun onReactContextInitialized(context: ReactContext) {
                        sendEvent(CLEVERTAP_PUSH_NOTIFICATION_CLICKED, payload.toWritableMap(), context)
                        mReactInstanceManager.removeReactInstanceEventListener(this)
                    }
                })
                if (!mReactInstanceManager.hasStartedCreatingInitialContext()) {
                    // Construct it in the background
                    mReactInstanceManager.createReactContextInBackground()
                }
            }
        }
    }

    private fun sendEvent(eventName: String, params: Any, context: ReactContext) {
        try {
            context.getJSModule(RCTDeviceEventEmitter::class.java)
                .emit(eventName, params)
        } catch (t: Throwable) {
            Log.e(TAG, t.localizedMessage)
        }
    }

    private fun <Any> Map<String, Any>?.toWritableMap(writableMap: WritableMap = Arguments.createMap()): WritableMap =
        if (this == null)
            writableMap
        else writableMap.apply wmap@{
                forEach { (k, v) ->
                    v?.apply {
                        this@wmap.putString(k, this.toString())
                    }
                }
            }
}

```

**Comment by gaston-munoz** [comment]
@piyush-kukadiya thanks for that!

I was also able to see this test project and it has worked for me, so I already have it working.

In case it works for someone, I'll leave it here

Thanks to those who have contributed

URL: https://github.com/parthdani/CleverTapReactKotlin

**Comment by Aditi3** [comment]
Glad it worked for you! Closing this thread

**Comment by xi3793-rpareek** [comment]
> @gaston-munoz For push notifications, launched from the killed state you need to implement the following piece of code, the reason being when the app starts from the killed state, React Native takes some time to initialize the JS Core. Due to this the push notification click callback fired by OS is missed in RN. The callback is fired earlier than RN listeners get set up.
> 
> In your `AppDelegate.m` file, under `didFinishLaunchingWithOptions` method pass `launchOptions` with initial properties as below
> 
> ```
> RCTRootView *rootView [[RCTRootView alloc] initWithBridge:bridge
>                                                    moduleName:@"ReactNativeExampleiOS"
>                                             initialProperties:launchOptions];
> ```
> 
> Now in the App.js file under App class, please make changes as below
> 
> ```
> class App extends React.Component {
> 
>   constructor(props){
>       super(props);
>       console.log('initial props:', props);
>       if(props.UIApplicationLaunchOptionsRemoteNotificationKey){
>     	 Alert.alert(JSON.stringify(props.UIApplicationLaunchOptionsRemoteNotificationKey)); // here you can get the payload 
>       }
>    }
> }
> ```

isn't working for ios when app is in killed state. we haven't find UIApplicationLaunchOptionsRemoteNotificationKey key.
