### ISSUE TITLE
unable to view inApp Messages in foreground android 12 and above

### ISSUE THREAD

**Issue by sunnyarain** [CleverTap/clevertap-react-native#313]
i have integrated Push and InApp notification which are working fine on Android version 9 for both foreground and Killed state.
 but on android 12 and above it not working properly as it showing just tray notification and on click it doesn't show InApp and listener is also not working in the JS.

further CleverTap.CleverTapPushNotificationClicked event is also not working on android 12 and 13

 "clevertap-react-native": "^1.0.1"
  "react-native": "0.64.0"

    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        ndkVersion = "20.1.5948944"
    }

**Comment by shivamsharma2710** [comment]
Hi @sunnyarain 

Thanks for reporting the issue. Will you please mention the which CleverTap Android SDK version you are using in gradle?

**Comment by sunnyarain** [comment]
Hello,
Thanks for reaching out its **4.7.5** version.

**Comment by shivamsharma2710** [comment]
Hi @rajeshzmoke

This behaviour is expected if you have not catered the [Notification trampolines handling](https://developer.clevertap.com/docs/android-push#android-12-changes) for Android 12 and above.

> Apps need to add the manual handling for android 12 onwards to inform the CleverTap Android SDK that the notification is clicked.

To achieve the same, add the following code in the `onNewIntent()` method of the **Launcher/Main Activity** in your android module:

```
class MainActivity : ReactActivity() {

override fun onNewIntent(intent: Intent?) {
   super.onNewIntent(intent)

   // On Android 12, Raise notification clicked event
   if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
       cleverTapDefaultInstance?.pushNotificationClickedEvent(intent!!.extras)
        }
    }
}
```

The same is referred in the [CleverTap Android Push doc](https://developer.clevertap.com/docs/android-push#sdk-changes).

**Comment by shivamsharma2710** [comment]
Hi @sunnyarain

This behaviour is expected if you have not catered the [Notification trampolines handling](https://developer.clevertap.com/docs/android-push#android-12-changes) for Android 12 and above.

> Apps need to add the manual handling for android 12 onwards to inform the CleverTap Android SDK that the notification is clicked.

To achieve the same, add the following code in the `onNewIntent()` method of the **Launcher/Main Activity** in your android module:

```
class MainActivity : ReactActivity() {

override fun onNewIntent(intent: Intent?) {
   super.onNewIntent(intent)

   // On Android 12, Raise notification clicked event
   if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
       cleverTapDefaultInstance?.pushNotificationClickedEvent(intent!!.extras)
        }
    }
}
```

The same is referred in the [CleverTap Android Push doc](https://developer.clevertap.com/docs/android-push#sdk-changes).

**Comment by shivamsharma2710** [comment]
Closing the ticket if you have further query please feel free to reopen the issue.

**Comment by sunnyarain** [comment]
it works. thanks for the help. 

can you help me with the In-App Notifications listner they are not getting trigger in the JS. do i need to implement some extra functionality?

CleverTapInAppNotificationButtonTapped and CleverTapInAppNotificationDismissed

**Comment by shivamsharma2710** [comment]
Will you please share your implementation for the same?

**Comment by shivamsharma2710** [comment]
@sunnyarain Thanks for the update.
