### ISSUE TITLE
Build error: 'CleverTap-iOS-SDK/CleverTap.h' file not found

### ISSUE THREAD

**Issue by cuttlas** [CleverTap/clevertap-react-native#314]
I get this error when building my react-native app. I'm using react-native 0.69.1 and the last version of this library.

This is my podfile:
```

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

$RNFirebaseAsStaticFramework = true

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

project 'myapp', 
  'Debug-Catalyst' => :debug, 
  'Release-Catalyst' => :release

target 'myapp' do
  use_frameworks!
  config = use_native_modules!
  pod 'CleverTap-iOS-SDK'
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  target 'myappTests' do
    inherit! :complete
  end
end
```

I've even tried to run "pod deintegrate" and remove the Podfile.lock file before running pod install, but I keep getting the error. Any ideas?

Thanks.

**Comment by nishant-clevertap** [comment]
Hi @cuttlas 

Can you try following changes and let us know if you are able to build and access files:
1. Import the header file like: `#import <CleverTapSDK/CleverTap.h>` in place of that.
OR
2. In Podfile, add `use_modular_headers!` and then import like: `@import CleverTapSDK;`

**Comment by cuttlas** [comment]
Using `#import <CleverTapSDK/CleverTap.h>` seems to be working.   Now I get the same error with the other import `'clevertap-react-native/CleverTapReactManager.h' file not found`.  

How should I import it?

Thanks

**Comment by nishant-clevertap** [comment]
@cuttlas  
You can directly import like this: `#import "CleverTapReactManager.h"` and if you are using modular header then you can use `@import CleverTapReact;` also

**Comment by nishant-clevertap** [comment]
Hi @cuttlas,
Are you still facing the issue?

**Comment by cuttlas** [comment]
Oh, sorry I forgot to reply.  No, it works now, your solution solved the problem. Thanks!
