### ISSUE TITLE
'CleverTapSDK/CleverTap.h' file not found

### ISSUE THREAD

**Issue by krishnaNl** [CleverTap/clevertap-react-native#32]
I am not able to complete the ios setup. I need a sample project. I am using clevertap-react-native": "^0.3.2"

**Comment by Aditi3** [comment]
I suggest try including **use_framework!** in the pod file and then build your project. 

CleverTapSDK is a dynamic framework, by specifying use_frameworks! you can make CocoaPods integrate to your project via frameworks instead of static libraries. 

Thanks!

**Comment by krishnaNl** [comment]
use_framework is already there
This is My Pod Config

-------------
# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Africa_CDC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

  # Pods for Africa_CDC
# this is very important to have!
rn_path = '../node_modules/react-native'
pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
pod 'React', path: rn_path, subspecs: [
  'Core',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket'
]

pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
pod 'Firebase/Core', '~> 5.15.0'
pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
 
 pod 'CleverTap-iOS-SDK'
 # pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native'

  target 'Africa_CDCTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Africa_CDC-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Africa_CDC-tvOS

  target 'Africa_CDC-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
# very important to have, unless you removed React dependencies for Libraries 
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
      end
    if target.name == "yoga"
      target.remove_from_project
    end
  end
end

**Comment by krishnaNl** [comment]
Can You share the smaple project in react native with the latest version of cleverTab.

**Comment by Aditi3** [comment]
Hey @krishnaNl 

We are in the process of updating the Example Project with the latest version of CleverTap.

Could you please write to support@clevertap.com and we can take this forward and help you in fixing the issue at earliest.

**Comment by Aditi3** [comment]
Hey @krishnaNl 

Here is the link of working Example for iOS Platform with the latest version of CleverTap React SDK
https://github.com/CleverTap/clevertap-react-native/tree/0.3.3/Starter

Sorry for the inconvenience caused.

Thanks,
Aditi

**Comment by krishnaNl** [comment]
From CleverTap-iOS-SDK Version 3.4.2, I have removed use_frameworks! in POD file. Now it is working for me

**Comment by Aditi3** [comment]
Good to know it worked for you.

Do you mind sharing what approach have you used to import CleverTap iOS Header?

**Comment by krishnaNl** [comment]
Same pod config I was already shared in this conversion. the only modification is to remove  use_frameworks!

**Comment by Aditi3** [comment]
Thank you for sharing.

Closing it. 

Thanks,
Aditi
