### ISSUE TITLE
Not getting callback in CleverTap.CleverTapPushNotificationClicked while application is in kill state. (iOS & Android)

### ISSUE THREAD

**Issue by Sid6022** [CleverTap/clevertap-react-native#320]
[https://github.com/CleverTap/clevertap-react-native/issues/167](url)

Tried above code but still not getting CleverTap.CleverTapPushNotificationClicked callback when application is in kill state (iOS & Android).

Followed this document for implement notification.
https://developer.clevertap.com/docs/android-push#push-notification-callback

can you please help me out ?

**Comment by shivamsharma2710** [comment]
Hi @Sid6022 

Please share the below details:
- CleverTap React Native SDK version
- Android version of the device you tested on?
- In which section of the application the callback for `CleverTap.CleverTapPushNotificationClicked` event is registered?

**Comment by Sid6022** [comment]
@shivamsharma2710  

CleverTap React-native **clevertap-react-native v 1.0.2**
Have checked in android 11 and 12 both OS. event not working in iOS 16.2

I have registered **CleverTap.CleverTapPushNotificationClicked** method in singleton class where all the firebase listener added.

**Comment by shivamsharma2710** [comment]
@Sid6022 To receive the callback in the **killed state**, your android's application class should extend the `CleverTapApplication` class instead of the `Application` class. Can you please confirm if you have followed this?

**Comment by Sid6022** [comment]
@shivamsharma2710  In android manifest we have added Application class because we have some packages which required to load in application class.

I followed this https://developer.clevertap.com/docs/react-native-quick-start-guide#android-integration

  
<img width="443" alt="Screenshot 2023-05-12 at 9 52 07 AM" src="https://github.com/CleverTap/clevertap-react-native/assets/939666/8c17a08a-f18e-40b6-9d38-d80d7c2e126e">

**Comment by shivamsharma2710** [comment]
@Sid6022 You can retain your Application class, but instead of extending from the default `Application` class, you should extend from `CleverTapApplication`. This will be the only modification required.

Your current implementation involves extending the default Application class as follows:

```
import android.app.Application;

public class MainApplication extends Application implements ReactApplication {
     @Override
  public void onCreate() {
    CleverTapAPI.setDebugLevel(CleverTapAPI.LogLevel.VERBOSE);
    ActivityLifecycleCallback.register(this);
    super.onCreate();
    
    //rest code
  }
}
```

To switch to extending `CleverTapApplication` instead of the default `Application` class, you would need to modify the implementation as shown below:

```
import com.clevertap.react.CleverTapApplication;

public class MainApplication extends CleverTapApplication implements ReactApplication {
     @Override
  public void onCreate() {
    CleverTapAPI.setDebugLevel(CleverTapAPI.LogLevel.VERBOSE);
    ActivityLifecycleCallback.register(this);
    super.onCreate();
    
    //rest code
  }
}

**Comment by Sid6022** [comment]
@shivamsharma2710  I have tried which you have shared above but still not receiving callback in **CleverTap.CleverTapPushNotificationClicked** listener.

Also tried this for android  [https://github.com/CleverTap/clevertap-react-native/commit/be647bab97081bbec8d8a8d7faaaa944bf4a877f](url)

**Comment by shivamsharma2710** [comment]
If you're facing this with android 12 or higher versions, please refer this [reply](https://github.com/CleverTap/clevertap-react-native/issues/313#issuecomment-1504558200).

**Comment by shivamsharma2710** [comment]
> @shivamsharma2710
> 
> CleverTap React-native **clevertap-react-native v 1.0.2** Have checked in android 11 and 12 both OS. event not working in iOS 16.2
> 
> I have registered **CleverTap.CleverTapPushNotificationClicked** method in singleton class where all the firebase listener added.


Could you please provide me with the code for your singleton class that registers the `CleverTap.CleverTapPushNotificationClicked `handler? Additionally, I want to know at which point this singleton class is instantiated.

Furthermore, we suggest registering the event as early as possible, such as, in the beginning of the Root component **(App.tsx)**, before it is mounted.

**Comment by Sid6022** [comment]
@shivamsharma2710 I have created one class where all the listener added in useEffect of class and that class I have added in navigation stack.


This one is singleton class
```
export default function DeeplinkHandling({ navigation, route }) {
 useEffect(() => {
 CleverTap.addListener(
        CleverTap.CleverTapPushNotificationClicked,
        event => {
          alert(JSON.stringify(event));
          console.log(
            'handleCleverTapEvent',
            CleverTap.CleverTapPushNotificationClicked,
            event,
          );
          // Handle notification link
        },
      );
 },[]}
}
```

and calling this class 

Home stack in app.js
 <DeeplinkHandling/>

**Comment by Sid6022** [comment]
> > @shivamsharma2710
> > CleverTap React-native **clevertap-react-native v 1.0.2** Have checked in android 11 and 12 both OS. event not working in iOS 16.2
> > I have registered **CleverTap.CleverTapPushNotificationClicked** method in singleton class where all the firebase listener added.
> 
> Could you please provide me with the code for your singleton class that registers the `CleverTap.CleverTapPushNotificationClicked `handler? Additionally, I want to know at which point this singleton class is instantiated.
> 
> Furthermore, we suggest registering the event as early as possible, such as, in the beginning of the Root component **(App.tsx)**, before it is mounted.

This method is already mounted in app.tsx still no callback, it's working fine when application is in active state.

**Comment by shivamsharma2710** [comment]
@Sid6022 I've noticed that you are using an alert in the callback to verify the click but the alert is not always reliable when the app was brought back to the foreground from the killed state after the notification click. Hence, I we recommend you to replace the alert with a toast, which is more consistent and reliable for testing purposes. Also, you can verify it by looking into the **Console logs.**

**Comment by shivamsharma2710** [comment]
@akashvercetti Please comment for the issue in iOS. Reporter is facing issue in both Android and iOS.

**Comment by Sid6022** [comment]
@akashvercetti  It's working fine as expected in iOS, after updating the SDK version with 1.0.3 but it's not working with android.

**Comment by Sid6022** [comment]
@akashvercetti  @shivamsharma2710  

Thanks for kind support, it's working fine in v.1.0.3

**Comment by Sid6022** [comment]
@shivamsharma2710 @akashvercetti  I'm getting callback in all of the app states, but after creating the release build or IPA I'm not getting callback in kill state. is there anything setup or I missed something to import ?
can you please help me out from this ?

**Comment by shivamsharma2710** [comment]
Hi @Sid6022 Is that behavior occurring on the Android or iOS platform?

**Comment by akashvercetti** [comment]
@Sid6022 I test ran our github sample app in a release build configuration using Xcode->Edit Scheme->Run->Info->Release config and was able to receive notifications in all states. 
Could you please check our sample app and compare the integration with yours?
Here is the link to the sample app: https://github.com/CleverTap/clevertap-react-native/tree/master/Example

**Comment by Sid6022** [comment]
@shivamsharma2710  @akashvercetti  Solved it's my bad, listener  was added in the useEffect so

**Comment by Sid6022** [comment]
> @Sid6022 I test ran our github sample app in a release build configuration using Xcode->Edit Scheme->Run->Info->Release config and was able to receive notifications in all states.
> Could you please check our sample app and compare the integration with yours?
> Here is the link to the sample app: https://github.com/CleverTap/clevertap-react-native/tree/master/Example

@akashvercetti  I'm using the hooks and I have implement all the things as per the document, still facing that kill state notification issue.  it's working fine in debug mode,  and in release mode working fine in some devices.

**Comment by shivamsharma2710** [comment]
@Sid6022 Based on my observation, it appears that you are using React Native's FCM package into your project, which is resulting in inconsistent behavior when it comes to the notification click handler.

As a workaround, the event registration, for the `CleverTap.CleverTapPushNotificationClicked` handler, needs to be placed in the `index.js` file instead of the `useEffect()` of the react native component.
This change is required because when a notification is clicked in the killed state, the FCM package creates a separate [Headless JS](https://reactnative.dev/docs/headless-js-android) service that operates independently of the main React component and does not mount the root component.
