### ISSUE TITLE
CleverTap.CleverTapPushNotificationClicked event is not working

### ISSUE THREAD

**Issue by BR0MBEERE** [CleverTap/clevertap-react-native#322]
I have a problem with getting the payload from the push notification.
When the app is closed and I open it by clicking on the push notification, the listener works and the method returns the data, however, when the app is open and I click on the notification, the method is not triggered.
I had the listener in the main app.tsx file.

**Comment by shivamsharma2710** [comment]
Hi @BR0MBEERE 

Please share the below details:

- CleverTap React Native SDK version?
- Android version of the device you are testing on?

**Comment by BR0MBEERE** [comment]
> Hi @BR0MBEERE
> 
> Please share the below details:
> 
> * CleverTap React Native SDK version?
> * Android version of the device you are testing on?

 * CleverTap React Native SDK: 1.0.2
 * Android version:  13

**Comment by shivamsharma2710** [comment]
@BR0MBEERE, Please review this [response](https://github.com/CleverTap/clevertap-react-native/issues/301#issuecomment-1504882660) and incorporate the necessary handling for devices running Android 12 and newer versions.

**Comment by BR0MBEERE** [comment]
Sorry for the late reply, but it worked, I was missing the "OnIntent" method.

**Comment by shivamsharma2710** [comment]
@BR0MBEERE Thanks for the update!
