### ISSUE TITLE
TypeError: null is not an object (evaluating 'CleverTapReact.setLibrary')

### ISSUE THREAD

**Issue by anta-semenov** [CleverTap/clevertap-react-native#334]
After updating Leanplum React Native SDK got this error
```
TypeError: null is not an object (evaluating 'CleverTapReact.setLibrary')
```

Seems like native module isn't initialized properly.

I have RN 0.72.0, clevertap-react-native v1.1.1
Clever ta

Do I need any additional steps other than calling `pod install`?

**Comment by kekami** [comment]
Getting this as well, did you manage to solve it? @anta-semenov
