### ISSUE TITLE
CleverTapPushNotificationClicked in IOS does not retrieve push notification title and message information.

### ISSUE THREAD

**Issue by BR0MBEERE** [CleverTap/clevertap-react-native#335]
When CleverTapPushNotificationClicked is invoked in android I get an object like this:
{ "data": { "nm": "test message", "nt": "test title", "wzrk_acct_id": "TEST-###-###-###", "wzrk_bc": "", "wzrk_bi": "2", "wzrk_cid": "", "wzrk_dt": "FIREBASE", "wzrk_id": "0_0", "wzrk_pivot": "wzrk_default", "wzrk_pn": "true", "wzrk_push_amp": "false", "wzrk_rnv": "false", "wzrk_ttl": "1604495979" }, "from": "618955247303", "messageId": "0:1604409582030477%6ed5e001f9fd7ecd", "sentTime": 1604409582026, "ttl": 86400 }

but on iOS the object looks like this: 
{"customExtras": {"W$dt": "APPLE", "W$id": "**********_********", "W$pivot": "wzrk_default", "W$rnv": false, "wzrk_acct_id": "TEST-###-###-###-####"}}}

I need the title and the message of the notification and I can't find how to get them in iOS.

**Comment by nishant-clevertap** [comment]
Hi @BR0MBEERE,
Currently we don't send notification title and message in iOS. Can you let us know what is your use case for getting the `nm` and `nt`  in iOS since the PN is rendered by iOS only?

**Comment by BR0MBEERE** [comment]
im working with the app inbox, but sometimes it takes too long for the inbox to update with the new message after you tapped the push notifications, so i wanted the data of the notification to show it to the user until the inbox update
i'm working with the appinbox, but sometimes it takes too long to update the inbox with the new message after tapping the push notifications, so i wanted the notification data to show the user something until the inbox is updated.
But if you say there is no way to get the data on iOS I guess my idea is out of the question.
Thanks.

**Comment by nishant-clevertap** [comment]
Hi @BR0MBEERE 
Please raise a product request for this, Thanks.
