### ISSUE TITLE
Duplicate class a.a.a found in modules jetified-installreferrer-2.2-runtime

### ISSUE THREAD

**Issue by AjayGol** [CleverTap/clevertap-react-native#341]
I have integration package in current app. We have already other package as well. 

Install version
==========
 "clevertap-react-native": "^1.1.2",
 
Build detail
=========
buildToolsVersion = "33.0.0"
minSdkVersion = 21
compileSdkVersion = 33
targetSdkVersion = 33
ndkVersion = "21.1.6352462"
googlePlayServicesAuthVersion = "16.0.1"
        

I have block by this issue 
==================
**Duplicate class a.a.a found in modules jetified-installreferrer-2.2-runtime (com.android.installreferrer:installreferrer:2.2) and jetified-sdk-3.6.1-runtime (com.smallcase.gateway:sdk:3.6.1)**

Thanks

**Comment by shivamsharma2710** [comment]
Hi @AjayGol 

I understand that you've encountered an issue related to the SmallCase SDK. This issue has actually been documented in the [developer documentation](https://developers.gateway.smallcase.com/docs/troubleshoot-android-sdk#3-we-are-facing-an-issue-with-installreferrer-library-version-22) along with the solutions provided by SmallCase.

To brief you, SmallCase proposes two potential solutions to resolve this problem:

1. **Downgrade the Installreferrer Library:** One option is to downgrade the installreferrer library to version 2.1. However, it's feasible as the CleverTap SDK relies on version 2.2 of the installreferrer library.
2. **Upgrade SmallCase SDK:** Alternatively, you can consider upgrading your **SmallCase SDK to version 3.8.6**. This update should help resolve the conflict and the issue you're encountering.

Closing the issue for now but if you have any further questions or need assistance, feel free to reopen the ticket.
