### ISSUE TITLE
Notification not showing on React Native Android

### ISSUE THREAD

**Issue by Mingeee** [CleverTap/clevertap-react-native#344]
Hey team!

Not sure what is wrong with the push notification - react native Android integration. It just stopped working early this week and nothing was changed when it was working previously. 

The UI is showing that the push successfully sent but nothing shows up.
 ![image](https://github.com/CleverTap/clevertap-react-native/assets/48815262/d5bb2a37-2584-4d03-b635-709ee90a94e0)
 
Check the logcat, there is a message saying that the message must set to the highest priority on firebase. The Importance is set to 5.
```
08-11 16:40:19.833  1183  1407 W ActivityManager: Background start not allowed: service Intent { cmp=nz.teddy.shop/io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService (has extras) } to nz.teddy.shop/io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService from pid=23205 uid=10343 pkg=nz.teddy.shop startFg?=false
08-11 16:40:19.835 23205 23205 E RNFirebaseMsgReceiver: Background messages only work if the message priority is set to 'high'
08-11 16:40:19.835 23205 23205 E RNFirebaseMsgReceiver: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=nz.teddy.shop/io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService (has extras) }: app is in background uid UidRecord{9c8bd4b u0a343 RCVR idle change:uncachedprocstateprocadj procs:0 seq(269355,260298)}
08-11 16:40:19.835 23205 23205 E RNFirebaseMsgReceiver:         at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1981)
```

I have tried the following: 
- upgrading and downgrading SDK between 1.1.0 / 1.1.1 / 1.1.2
- using two different phones Android 10 and Android 13. Both Samsung
- tried it on emulators
- making sure the notification settings are turned on
- double check the channel id
- checking firebase server key and id that was entered into CleverTap admin
- upgrading and downgrading Android SDK between 4.75 and 5
    - when upgrading to 5. The app will just close immediately on start.
- I tried adding the Notification Trampolines changes based on the recommendations in the doc. The app just can't be build. 
```
public class MainActivity extends ReactActivity {

   @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);

        CleverTapAPI cleverTapDefaultInstance = CleverTapAPI.getDefaultInstance(getApplicationContext());
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            if(cleverTapDefaultInstance != null) {
                 // On Android 12 and onwards, raise notification clicked event and get the click callback
                 cleverTapDefaultInstance.pushNotificationClickedEvent(intent.getExtras());
            }
        }
    }
}
```

Package details
"react-native": "0.70.6", 
"clevertap-react-native": "^1.1.0", // have tried 1.1.1 and 1.1.2

build.gradle dependencies 

```
 implementation 'com.clevertap.android:clevertap-android-sdk:4.7.5'  // have tried all the 5 version and 4.69 
    implementation 'com.google.firebase:firebase-messaging:23.0.6'
    implementation 'androidx.core:core:1.4.0'
    implementation 'androidx.fragment:fragment:1.3.6'
```

Perhaps, is there any logging I can see in the CleverTap admin?

**Comment by shivamsharma2710** [comment]
Hi @Mingeee 

Please share the SDK logs you receive for Android platform once you send a push from dashboard.

To generate the logs, open the project in the Android Studio and follow the below instructions:
- Set the debugLevel of the SDK to Verbose using the `CleverTap.setDebugLevel(3);` from the root component of your application. Check [documentation](https://developer.clevertap.com/docs/react-native-advanced-features#debugging) for reference. 
- Launch the application on a Android device.
- Send a test push from dashboard.
- To search the associated logs, use **CleverTap** tag in the search bar of the LogCat window.

**Comment by Mingeee** [comment]
@shivamsharma2710 Thanks! I will do that now and get back to you. ^.^

**Comment by Mingeee** [comment]
@shivamsharma2710 Thanks for the tips! 
I have found the issue. 
I was kinda dumb by putting in lowercase notification id channel. 

The id declare in the app was uppercase. 😓

**Comment by shivamsharma2710** [comment]
Thanks @Mingeee for the update.
