### ISSUE TITLE
Android build failed when upgraded from 0.2.6 to 0.3.4

### ISSUE THREAD

**Issue by code76kb** [CleverTap/clevertap-react-native#35]
/.gradle/caches/transforms-1/files-1.1/clevertap-android-sdk-3.5.1.aar/6e3c052bbc8c823383d56efe1aacd7fc/res/layout-land/inbox_carousel_layout.xml:14:35-64: AAPT: No resource found that matches the given name (at 'layout_above' with value '@id/timestamp_relative_layout').

**Comment by nikoloz110** [comment]
Same with me. build fails on from 0.3.0 and up. react native version 0.51.0

**Comment by darshanclevertap** [comment]
@code76kb @nikoloz110 This issue will be fixed in the next version, I would suggest staying on v0.3.0 for now.

**Comment by nikoloz110** [comment]
did you mean stay on v.0.2.6?  because v.0.3.0 does not build. (and other
build after that).
And can you give me rough estimate when will you fix it? My company needs
to use Inbox feature, which is available in  0.3.0 and up.

Thanks for such quick reply.

**Comment by darshanclevertap** [comment]
@nikoloz110 Yes sorry, stay at v0.2.6. ETA for the next release is the end of August.

**Comment by MugeshM** [comment]
I am using v0.3.4 and facing same issue. @darshanclevertap Any Idea when this will be fixed?

**Comment by darshanclevertap** [comment]
@MugeshM @nikoloz110 **Update** - We are going to fix this in the upcoming release v0.3.5 which will be released before the end of this week.

**Comment by darshanclevertap** [comment]
@MugeshM @nikoloz110 @code76kb This has been fixed in v0.3.5. Closing this issue.
