### ISSUE TITLE
iOS notification in Foreground

### ISSUE THREAD

**Issue by ramssutharr** [CleverTap/clevertap-react-native#353]
cannot receive push notifications in foreground & docs are not clear.

**Comment by darshanclevertap** [comment]
@ramssutharr can you please provide some details here so that we can help?
- CleverTap React Native SDK version
- Platform - Android/iOS?
- Documentation links?
- Error logs/screenshots?

**Comment by ramssutharr** [comment]
@darshanclevertap i am facing the issue on iOS i have followed the steps provided on official website of clevertap and there is no error. the only issue is im not receiving notifications in foreground , im using latest sdk of RNCleverTap.  and also there are syntax error when setting up the iOS part in step 4 - [https://developer.clevertap.com/docs/push-notifications-ios] . i have already firebase notifications configured with notifee library which handle both case and also Notification Extension Service is added for foreground notification. does it has to do anything with cleverTap integration  ?

**Comment by nishant-clevertap** [comment]
Hi @ramssutharr,

Can you follow the steps mentioned here to get notifications in foreground and let me know if it works or not. You need to add one delegate method in your AppDelegate to get notifications in foreground: https://developer.clevertap.com/docs/react-native-push-notification#ios-foreground-notifications

**Comment by ramssutharr** [comment]
@nishant-clevertap done everything , still not getting notification in foreground. I’m getting notifications in foreground and background from firebase & notifee. also my existing notification extension service is getting triggered if i click on background notification received from cleverTap.

**Comment by nishant-clevertap** [comment]
@ramssutharr Can you share your AppDelegate file if possible to check if everything is added?

**Comment by nishant-clevertap** [comment]
@ramssutharr 
As I can see you have not conforms to `UNUserNotificationCenterDelegate` in AppDelegate as mentioned in the doc. You can refer this example on how to conforms delegate: https://github.com/CleverTap/CTNotificationService/blob/master/Example/CTNotificationServiceExample/AppDelegate.m#L6

Also you need to add the `UNUserNotificationCenter` delegate to self as added here on line no 24: https://github.com/CleverTap/CTNotificationService/blob/master/Example/CTNotificationServiceExample/AppDelegate.m#L24

Try adding these 2 changes then it will work.

**Comment by ramssutharr** [comment]
@nishant-clevertap thank you so much got it working.
