### ISSUE TITLE
Allow configuring the first tab title on showInbox

### ISSUE THREAD

**Issue by MarwahBakoor** [CleverTap/clevertap-react-native#356]
The first tab title on the showInbox feature is not configurable

**Comment by MarwahBakoor** [comment]
[PR ](https://github.com/CleverTap/clevertap-react-native/pull/342) to allow configuring it

**Comment by shivamsharma2710** [comment]
Hi @MarwahBakoor 

Thank you for submitting a PR to support these changes. We plan to merge your PR with the next release scheduled for the end of October. We will notify you if we decide to do it earlier.
