### ISSUE TITLE
can't find the logout() equivalent of clevertap-web-sdk for react native. what to do if a user logs out of my app

### ISSUE THREAD

**Issue by Balaram-Singh** [CleverTap/clevertap-react-native#357]

**Comment by shivamsharma2710** [comment]
Hi @Balaram-Singh 

Please review the [CleverTap documentation](https://developer.clevertap.com/docs/user-profiles-react-native) on how to manage user profiles. If you have any further questions or if this doesn't address your query, please raise a support request from the CleverTap dashboard.

**Comment by Balaram-Singh** [comment]
Hi @shivamsharma2710 

Could you provide a more specific link

https://developer.clevertap.com/docs/user-profiles-react-native#:~:text=However%2C%20you%20may%20need%20to%20add%20additional%20user%20properties%20to%20the%20user%20profile%20such%20as%20gender%2C%20date%20of%20birth%2C%20and%20so%20on
