### ISSUE TITLE
"React-native" how to get payload from Notification 

### ISSUE THREAD

**Issue by nguyenductoan1995** [CleverTap/clevertap-react-native#36]
I'm receiving notifications on mobile but not able to read its payload.

**Comment by Aditi3** [comment]
Hey @nguyenductoan1995 

Seems similar to #31. 

Hope this helps.

Thanks,
Aditi

**Comment by nguyenductoan1995** [comment]
> Hey @nguyenductoan1995
> 
> Seems similar to #31.
> 
> Hope this helps.
> 
> Thanks,
> Aditi

But i need Method for handel on react-native , this issue don't resolve problem

**Comment by sangupandi** [comment]
You will get the redirect URL as like as DeepLinking. 
 Linking.getInitialURL().then((url) => {}) ;

**Comment by Aditi3** [comment]
Closing it, if you need further help you can also write to support@clevertap.com.

Thanks!
