### ISSUE TITLE
[Question] Expo Config Plugin

### ISSUE THREAD

**Issue by rizaldirnm** [CleverTap/clevertap-react-native#362]
Hi guys, have you heard about **Expo Config Plugins**?

Its help to up and running that require more step after install package in `expo prebuild`

is there any planing to write Expo Config Plugin in `clavertap-react-native` ?

[Expo Config Plugin Docs](https://docs.expo.dev/config-plugins/introduction/)

**Comment by darshanclevertap** [comment]
@rizaldirnm CleverTap does not support Expo Apps officially. We will have to revisit Expo and Expo Config plugins before we decide to put in some effort into this. 

Could you please let us know if you are using CleverTap React Native SDK with your Expo app?

**Comment by rizaldirnm** [comment]
in current situation we already implement both ios/android using Clevertap SDK. But now we in the middle of research to move into multi platform such as Expo. I am happy to hear if Clevertap implement Expo Config Plugin.

**Comment by darshanclevertap** [comment]
@rizaldirnm So CleverTap React Native SDK does not work well with Expo. This is because Expo has a very restricted way of building plugins. If you are still researching on the Expo, I would suggest going with React Native so that you can fully use CleverTap's features with our React Native SDK.

**Comment by rizaldirnm** [comment]
Ok thank you @darshanclevertap for quick response 🥂

**Comment by iykazrji** [comment]
Hi @darshanclevertap! Given that react native now officially recommends Expo as the framework of choice for React Native, are there any plans to have an official Config Plugin for clevertap? 

Thanks!

**Comment by satyam-capcons** [comment]
Hi, @darshanclevertap, React Native docs now officially recommend expo framework for app development, it would be very helpful if a config plugin gets made for clevertap. Without it, the integration is not straightforward.
