### ISSUE TITLE
push impression not working with "W$id" = "0_0"

### ISSUE THREAD

**Issue by Balaram-Singh** [CleverTap/clevertap-react-native#364]
{
    "W$dt" = APPLE;
    "W$id" = "0_0";
    "W$pivot" = "wzrk_default";
    "W$rnv" = 1;
    aps =     {
        alert =         {
            body = "some msg";
            title = "some ttl";
        };
        "mutable-content" = 1;
    };
    payload = "{\"type\":\"info\",\"data\":{\"title\":\"some title\",\"body\":\"some body message\",\"btns\":{\"positive\":{\"txt\":\"Ok\"},\"negative\":{\"txt\":\"Cancel\"}}}}";
    "wzrk_acct_id" = "XXX-XXX-XXXX";
}

**Comment by darshanclevertap** [comment]
@Balaram-Singh the "wzrk_id" field is set to "0_0" only for test push notifications. For test push notifications we do not raise the Push Impression event. Please create a campaign and send a push notification to test the Push Impression event.
If you have any other queries regarding this, I would suggest raising a Support ticket from the dashboard or via this link -> https://help.clevertap.com/hc/en-us

**Comment by maurusrv** [comment]
> For test push notifications we do not raise the Push Impression event.
this is a bit harder to find out, but thanks! Maybe it would be better to indicate this in the docs.
