### ISSUE TITLE
changeCredentials In React native

### ISSUE THREAD

**Issue by Thronie** [CleverTap/clevertap-react-native#37]

**Comment by Thronie** [comment]
Hi, 

How we will change credentials for development and production environment in react native.

**Comment by Aditi3** [comment]
Hey @Thronie 

I am assuming that you wish to set credentials for development and production programmatically, you can do so in your App Delegate, in `application:didfinishlaunchingwithoptions:`

Here is the helpful code snippet for implementing the same:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
// add `DEBUG=1` to your Debug build preprocessor settings  
 #ifdef DEBUG
        [CleverTap setCredentialsWithAccountID:@"Your development account ID here" andToken:@"Your  development account token here"];
 #else
       [CleverTap setCredentialsWithAccountID:@"Your production account ID here" andToken:@"Your production account token here"];
  #endif

      [CleverTap autoIntegrate];
      ...
      return YES;
}
```

Hope this helps.

**Comment by gciluffo** [comment]
Does anyone know of a way to configure the credentials during runtime? In other words is there a React Native method exposed to do this? Or do the credentials have to be configured during build time? @Aditi3
