### ISSUE TITLE
Support for Android SDK 6.1.0 due to `Shutdown Notice of Mi Push Service Outside Mainland China`

### ISSUE THREAD

**Issue by CatWithNineLives** [CleverTap/clevertap-react-native#370]
More of a question than an issue, due to the recent announcement on [Shutdown Notice of Mi Push Service Outside Mainland China](https://dev.mi.com/distribute/doc/details?pId=1777) and Clevertap's notice : 
[Discontinuation of Xiaomi Push Service](https://developer.clevertap.com/docs/discontinuation-of-xiaomi-push-service)
on updating the android SDK to `v6.1.0`(estimated to be available on 20th February 2024), 

can you share if there are any plans to add support for Android SDK `v6.1.0` to this `clevertap-react-native` library too.

And when can we expect the update, thanks!

**Comment by Anush-Shand** [comment]
@CatWithNineLives update to`clevertap-react-native` to support v6.1.0 has been prioritised and should be out in a couple of weeks. For now you can simply remove the Xiaomi integration from your app by following this doc https://developer.clevertap.com/docs/discontinuation-of-xiaomi-push-service#steps-to-remove-the-xiaomi-sdk-usage--
