### ISSUE TITLE
Integration checklist issue with SDK

### ISSUE THREAD

**Issue by wikramdas** [CleverTap/clevertap-react-native#374]
After successfully integrating CleverTap into my React Native app and confirming the initialization of the SDK, I encountered an issue upon returning to the CleverTap dashboard. Despite ensuring all necessary fields are correctly configured, the dashboard consistently prompts to 'continue with the checklist first.' It appears that the CleverTap SDK initialization is not effectively linking the app with the CleverTap dashboard. I require assistance in resolving this matter.

<img width="601" alt="Screenshot 2024-02-20 at 3 12 01 PM" src="https://github.com/CleverTap/clevertap-react-native/assets/45879181/8b5a6774-c606-4cf2-886c-9e1f98a1cb63">

**Comment by darshanclevertap** [comment]
@wikramdas Please raise a support ticket on our [Help Center](https://help.clevertap.com/hc/en-us) and our support team will help you with this.

**Comment by Raaz45** [comment]
same problem

**Comment by darshanclevertap** [comment]
@Raaz45 Please raise a support ticket on our [Help Center](https://help.clevertap.com/hc/en-us) and our support team will help you with this

**Comment by Raaz45** [comment]
i got solution for this problem.
It was country region we have to use `<meta-data android:name="CLEVERTAP_REGION" android:value="eu" />` problem will be solved
