### ISSUE TITLE
Pods of clevertap-react-native conflicts with react-native-fast-image.

### ISSUE THREAD

**Issue by ebellumat** [CleverTap/clevertap-react-native#38]
Hello,

I use  "react-native-fast-image": "^7.0.2" in my project, but the Clevertap uses a OLD version of  SDWebImage/GIF (~> 4.0) which depends a old version of SDWebImage/Core (= 4.0.0), 

The Fast image use SDWebImage/Core (= 5.0.4). Please update clevertap-react-native to use the last version of dependency. This lib broken the entire project. 

![image](https://user-images.githubusercontent.com/26942680/64024466-da116880-cb10-11e9-84d1-100fd22149ef.png)

**Comment by ebellumat** [comment]
I check the Clevertap-iOS-SDK, the clevertap-react-native uses a 3.4.2 version, but the Clevertap-iOS-SDK version 3.6.0 uses the SDWebImage version 5.0. Please update this.

**Comment by Aditi3** [comment]
Hey @ebellumat 

We already have a plan to update SDWebImage 5.x in the upcoming version of the SDK.

The release with SDWebImage 5.x will be available soon. We will keep you posted.

Thanks,
Aditi

**Comment by Aditi3** [comment]
Hey, @ebellumat

We have released support for SDWebImage version 5.x

Here is the link of the latest release that comes with the SDWebImage 5.x support
https://github.com/CleverTap/clevertap-react-native/releases/tag/0.3.5

Thanks!
