### ISSUE TITLE
undefined.CleverTapPackage in react native 0.68.2

### ISSUE THREAD

**Issue by satyamtothenew** [CleverTap/clevertap-react-native#381]
In CleverTap new version we have encounter a error,
<img width="990" alt="image" src="https://github.com/CleverTap/clevertap-react-native/assets/133632982/2dbdc5eb-d092-4129-abf8-a8f9b1b8b1ea">

-----------------------------

android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:15: error: 
package does not exists
undefined.CleverTapPackage;

-----------------------------

It is causing this issue in below <0.70 react-native

Versions Details:-
clevertap-react-native: ( 2.1.0, 2.0.0 )
react-native: 0.68.2

**Comment by satyamtothenew** [comment]
Solution:-

package name line missing in AndroidManifest file,
after adding 
 package="com.clevertap.react" in manifest

it works fine👍,

i think because in new version of react-native it picked CleverTapPackage path from build namespace but in <0.70 it worked by defining the package in mainfest,


<img width="582" alt="image" src="https://github.com/CleverTap/clevertap-react-native/assets/133632982/3296879b-0206-48c9-acfb-6b61714539df">

**Comment by nguyenductoan1995** [comment]
i have same issue pls help me @satyamtothenew

**Comment by satyamtothenew** [comment]
follow solution steps: https://github.com/CleverTap/clevertap-react-native/issues/381#issuecomment-1993719501
goto node_modules/clevertap-react-native/android/src/main/AndroidManifest.xml
add package="com.clevertap.react" line below of xmlns:tools line

it will work

**Comment by satyamtothenew** [comment]
@nguyenductoan1995 use above solution 
go into node_modules/clevertap-react-native/android/src/main/AndoridMainfest.xml
add package="com.clevertap.react" line below xmlns:tools line

**Comment by nguyenductoan1995** [comment]
> package="com.clevertap.react"

thank you Sr very muck, this issuse was resolve @satyamtothenew
