### ISSUE TITLE
How to use it for push notification?

### ISSUE THREAD

**Issue by rahulnainwalttn** [CleverTap/clevertap-react-native#384]
Can we use clevertap-react-native for push notification? For our use case, we have multiple shows scheduled at different times and user can set a reminder for shows. So we needed a way to set push notification for particular user and get list of pending push notifications for that particular user?
<img width="511" alt="Screenshot 2024-03-29 at 9 32 57 AM" src="https://github.com/CleverTap/clevertap-react-native/assets/136161024/35eb2c73-2e12-44e4-9e36-2fa9d4fb95cd">

**Comment by darshanclevertap** [comment]
@rahulnainwalttn A short answer is yes Push notifications do work with CleverTap React Native as well.
For your particular use case, I would suggest [you raise a support request with our team using this link. ](https://help.clevertap.com/hc/en-us)
One of our Support team members can help you with your use case.
The Issues section of this repo is to discuss any technical problems with the SDK like bugs, crashes, new version information, etc
