### ISSUE TITLE
Need to know the behavior of In App Messages. 

### ISSUE THREAD

**Issue by kiranleo1** [CleverTap/clevertap-react-native#385]
Hello Team, 

react-native version 0.73.4
Clevertap version 2.1.0

I'm encountering an issue with triggering In-App Messages from campaigns while setting filters for specific screens. Here's a brief overview of the problem:

Issue Description:
When triggering a test In-App Message from campaigns and setting a filter to trigger on a particular screen, the message is not appearing as expected.

Observations:
Upon triggering the test, the notification panel displays an unexpected behavior, as shown in the attached image. However, upon tapping on the notification, the expected behavior is observed.

![Screenshot_1711703839](https://github.com/CleverTap/clevertap-react-native/assets/145327406/c0a8aa24-6d81-45f9-acf1-91975853f2b3)

**Comment by Anush-Shand** [comment]
@kiranleo1 Could you please further elaborate on what is the unexpected behaviour? It is unclear from the above comment.

Could you also please mention the devices on which the issue exists and share the reproduction steps

**Comment by kiranleo1** [comment]
> @kiranleo1 Could you please further elaborate on what is the unexpected behaviour? It is unclear from the above comment.
> 
> Could you also please mention the devices on which the issue exists and share the reproduction steps

Thanks for your response.

I am facing the issue is like, When i am try to send test in app message (template) from Campaigns it is coming in device notification drawer. And i am expecting  the behaviour is like if my Campaigns target segment is set by when user dose by event property then only in app message should trigger. 
And now in app message is coming in notification drawer like above image. and if i am clicking on the notification then its open the popups in application 

Device : android 13 (pixel emulator)

Reproduce steps
-  send test in app from Campaigns
- in app notification coming in notification drawer
- click on notification, then it will opens a popup in application

Please help. Thank you

**Comment by Anush-Shand** [comment]
@kiranleo1 
Send test (Preview and test) is used to see whether the created InApp looks fine from a UI perspective only and the above mentioned behaviour is expected.
The user property qualification will work when the campaign is published. If you want to test the user property qualification, you can create a campaign for a user property that is only passed by your device and then create a campaign only for yourself.

**Comment by kiranleo1** [comment]
> @kiranleo1 Send test (Preview and test) is used to see whether the created InApp looks fine from a UI perspective only and the above mentioned behaviour is expected. The user property qualification will work when the campaign is published. If you want to test the user property qualification, you can create a campaign for a user property that is only passed by your device and then create a campaign only for yourself.

Thanks you so much @Anush-Shand  it is working. Also can you please help me for in app message should show once if i am showing in particular screen. now it is rendering again and again when I am navigation to that screen.

**Comment by Anush-Shand** [comment]
@kiranleo1 You can configure this in the delivery preferences of the campaign. Please refer to this documentation for the same
https://docs.clevertap.com/docs/web-native-display-create-message#delivery-preferences
