### ISSUE TITLE
minSdkversion miss-match library have 19 and RN@0.74.x have 23

### ISSUE THREAD

**Issue by chawkip** [CleverTap/clevertap-react-native#399]
minSdkversion miss-match library have 19 and RN 0.74.x have 23

**Comment by Anush-Shand** [comment]
@chawkip Could you please share the complete stacktrace of this compile issue?

**Comment by audrius-savickas** [comment]
Why was this closed? This still happens

**Comment by Anush-Shand** [comment]
@chawkip Could you elaborate the issue and as to how you went about fixing it?
