### ISSUE TITLE
Does not work with react-native version 0.74.5

### ISSUE THREAD

**Issue by nat-gaurav-saini** [CleverTap/clevertap-react-native#426]
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: nat-store-app@1.0.0
npm error Found: react-native@0.74.5
npm error node_modules/react-native
npm error   react-native@"0.74.5" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react-native@"^0.71.0" from clevertap-react-native@3.0.0
npm error node_modules/clevertap-react-native
npm error   clevertap-react-native@"3.0.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/gaurav/.npm/_logs/2024-10-16T08_14_09_442Z-eresolve-report.txt
npm error A complete log of this run can be found in: /Users/gaurav/.npm/_logs/2024-10-16T08_14_09_442Z-debug-0.log

**Comment by kushCT** [comment]
@nat-gaurav-saini 
Have you tried `npm install clevertap-react-native@3.0.0 --legacy-peer-deps`? 
Since clevertap-react-native@3.0.0 will work with react-native@0.74.5, you can try overriding the peer dependency warning by using the `--legacy-peer-deps` flag.

**Comment by nat-gaurav-saini** [comment]
This works for adding dependency but fails when doing a eas build because we cannot overwrite their build step.

PS: I know expo is not supported but I am trying to develop plugins with the help of our CT CSM.

**Comment by kushCT** [comment]
@nat-gaurav-saini Noted the issue
We will resolve this with the upcoming release

**Comment by piyush-kukadiya** [comment]
Fixed in release [3.1.0](https://github.com/CleverTap/clevertap-react-native/releases/tag/3.1.0)
