### ISSUE TITLE
[Inbox] How to capture the click of the buttons?

### ISSUE THREAD

**Issue by ebellumat** [CleverTap/clevertap-react-native#44]
I have inbox message like this, but when i click on generated button, nothing happen. How can i implement an action for this button?  The button is called "Aplicar Cupom".

![image](https://user-images.githubusercontent.com/26942680/64287749-e8a7b780-cf36-11e9-8a2d-ad4674d66d66.png)

Thanks.

**Comment by Aditi3** [comment]
Hey @ebellumat 

Check out our App-Inbox documentation: https://developer.clevertap.com/docs/ios#section-app-inbox

If you need further help request you to write to support@clevertap.com so that we can take the discussion forward and assist you.

Thanks,
Aditi

**Comment by ebellumat** [comment]
But i'm using React Native wrapper. Native code implementation will not work for my case...
