### ISSUE TITLE
How to close inbox programmatically?

### ISSUE THREAD

**Issue by ebellumat** [CleverTap/clevertap-react-native#46]
Today we have an option to open Inbox, but no options to close inbox.

My buttons on In App Inbox have actions, but the user have to close the Inbox Modal manually to see the action happens. How to close inbox when the user call an action?

Without this, looks like the app are unresponsive.

![image](https://user-images.githubusercontent.com/26942680/65149002-afbc1800-d9f7-11e9-8763-0dcca1ebfca5.png)

Regards, Erasmo.

**Comment by ebellumat** [comment]
Any update?

**Comment by Aditi3** [comment]
Closing this as it is being taken up by Support. 

Thanks!
