### ISSUE TITLE
Notification not showing on Android

### ISSUE THREAD

**Issue by ianrajs** [CleverTap/clevertap-react-native#48]
I have integrate my clevertap with push notification. And I have use the right FCM Sender ID and FCM Legacy Server Key.
When I'm trying to send test push notification on Android, It says successfully sent. But the notification now showing in my device

**Comment by darshanclevertap** [comment]
@ianrajs Have you set up a Notification Channel in your app? Follow [this documentation](https://developer.clevertap.com/docs/android#section-push-notifications-for-android-o) to understand Notification Channels in Android.

**Comment by ianrajs** [comment]
Hi @darshanclevertap,
I have set up notification channel in my app like this:
`CleverTap.createNotificationChannel('test-channel', 'test-channel', 'test-channel', 5, false);`

I develop the app using react native btw

**Comment by darshanclevertap** [comment]
And you are using `test-channel` while creating the Push Notification campaign in the dashboard?

**Comment by ianrajs** [comment]
Yes I do

**Comment by darshanclevertap** [comment]
Please set the debug level to 3 and share with me the Android Studio console logs? From app launch to when you send us a push notification. That would shed some light on what is happening with your app.

**Comment by darshanclevertap** [comment]
@ianrajs Were you able to fix this issue or are you still dealing with it?

**Comment by uraniumreza** [comment]
hey @darshanclevertap; I've created a 'test-channel' and sending a test notification from clevertap dashboard! Interestingly I'm getting this on android studio logcat - 
`
D/RNFMessagingService: onMessageReceived event received
D/RNFirebaseMessaging: Received new message
`
But nothings showing on my emulator Notification tray! What's going wrong?

**Comment by darshanclevertap** [comment]
@uraniumreza Are you using our FCMMessageListener or are you rendering the Push notification on your own?

**Comment by uraniumreza** [comment]
Yeah, I'm using FCMMessageListener; my issue has been resolved. Thanks @darshanclevertap

**Comment by dattaprasadPegasus** [comment]
@darshanclevertap I am getting same issue. can you please guide....

**Comment by darshanclevertap** [comment]
@dattaprasadPegasus Have you set up a Notification Channel in your app? Follow this [documentation](https://developer.clevertap.com/docs/android#section-push-notifications-for-android-o) to understand Notification Channels in Android.

**Comment by brunofrigeri** [comment]
I'm getting the same issue, how do you guys solved it?

**Comment by andrewdazs** [comment]
This is happening with me too. I'm sending the push notification to my Android device and the notification didn't show up, the only thing I receive is this message: `RNFMessagingService  D  onMessageReceived event received`

Someone can help me?

**Comment by Arun-paramasivam** [comment]
@brunofrigeri @andrewdazs hope this helps you.

[https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTV4CHANGES.md#-firebase-messaging-changes](https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTV4CHANGES.md#-firebase-messaging-changes)

They mentioned it here too
[https://developer.clevertap.com/docs/android#section-push-notifications](https://developer.clevertap.com/docs/android#section-push-notifications)

I faced with a similar issue as I updated my package and didn't notice these changes for android.

**Comment by iAtharZaib** [comment]
Hi there. Facing same issue. App notifications working fine. But not the ones sent from clever tap.

**Comment by divyaYK** [comment]
> FCMMessageListener

Hi, @darshanclevertap  
I'm using FCMMessageListener and tried sending a test notification from the dashboard through an FCM token.
This works when the Android app is running in the foreground but not when the app is running in the background or when killed. What am I missing here?
