### ISSUE TITLE
Unable to build the project on android

### ISSUE THREAD

**Issue by ahishek** [CleverTap/clevertap-react-native#5]
Hey, I get this error when I try to run my android project
`error: package com.clevertap.android.sdk does not exist
import com.clevertap.android.sdk.CleverTapAPI;
`

Clevertap Android sdk version - 3.1.4

Can you help?

**Comment by pwilkniss** [comment]
@ahishek   have you added the sdk to your app dependencies ?
see https://github.com/CleverTap/clevertap-react-native/blob/master/docs/install.md#android

if you've done that and are still having problems, please drop a line with details to support at clevertap.com
