### ISSUE TITLE
Module 'CleverTapSDK' not found.

### ISSUE THREAD

**Issue by LonelyCpp** [CleverTap/clevertap-react-native#53]
I have this line in my pod file 
`pod 'clevertap-react-native', path: '../node_modules/clevertap-react-native'`

since im using firebase crashlytics, i cant link the SDK using `use_frameworks!` in the pod file. So i manually linked the sdk as shown here - https://developer.clevertap.com/docs/ios-quickstart-guide

but i get `(path to project) /node_modules/clevertap-react-native/ios/CleverTapReact/CleverTapReactManager.m:9:9: Module 'CleverTapSDK' not found`

**Comment by Aditi3** [comment]
Hey @LonelyCpp 

If your project configuration doesn't allow you to include **use_frameworks!** in the podfile.

I suggest installing our CleverTap React Native library with the option iOS without podspec.

Helping link for the same: https://github.com/CleverTap/clevertap-react-native/blob/master/docs/install.md#ios-without-podspec

Also, do to check out our [Demo Application](https://github.com/CleverTap/clevertap-react-native/tree/master/Starterrl) to verify the installation.

**Comment by LonelyCpp** [comment]
I now have both `pod 'clevertap-react-native'` and `pod 'CleverTap-iOS-SDK'` in my pod file. 

Not sure why that fixed the issue.

**Comment by felippepuhle** [comment]
I've tried both ways and still getting this same error, using a custom fork for now.

**Comment by sergeymorkovkin** [comment]
Tried both options and still having same error. Any advice?

**Comment by felippepuhle** [comment]
@sergeymorkovkin it'll probably work if you add `use_frameworks!` to your `Podfile`, but we didn't do that... we're still using a custom fork:

```
    "clevertap-react-native": "git+https://github.com/ebellumat/clevertap-react-native",
```

**Comment by sergeymorkovkin** [comment]
@felippepuhle Thanks for sharing! Will definitely use your repo, but from my perspective it's probably better to use [patch-package](https://www.npmjs.com/package/patch-package). Give it a try and you'll leverage all most recent commits from the original repo.

**Comment by Aditi3** [comment]
Hi @sergeymorkovkin 

Alternatively, in your Podfile, you can add **use_modular_headers!** to enable the stricter search paths and module map generation for all of your pods, or you can add :modular_headers => true to a single pod declaration to enable for only that pod. 

Give it a try and let us know how it goes for you.

**Comment by deepak-bm-ai** [comment]
pod file:
  pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native', modular_headers: true 
  pod 'CleverTap-iOS-SDK', modular_headers: true

AppDelegate.m:
 @import CleverTapSDK;
 @import CleverTapReact;

worked for me. Thanks @LonelyCpp

**Comment by shrmaky** [comment]
I was integrating in React Native `0.65`

In Podfile -

pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native', modular_headers: true
pod 'CleverTap-iOS-SDK', modular_headers: true

In AppDelegate.m, changed to -
```
#import <CleverTap-iOS-SDK/CleverTap.h>
#import <clevertap-react-native/CleverTapReactManager.h>
```

I am able to build now.
