### ISSUE TITLE
Update the iOS SDK to 3.7.0

### ISSUE THREAD

**Issue by vogosamvelraja** [CleverTap/clevertap-react-native#55]
There is an issue clevertap iOS SDK 3.6.0 for iOS 13.

https://stackoverflow.com/questions/58064157/ios13-crash-uiwindowscene-enumeratewindowsincludinginternalwindowsonlyvisibl

Kindly update this. Or steps to update it. we are blocked on this now in our production app.

**Comment by Aditi3** [comment]
Hey @vogosamvelraja 

We have already released the React-Native v0.3.5 in sync with our latest release that is CleverTap iOS SDK v3.7.0

Reference Change Log: https://github.com/CleverTap/clevertap-react-native/blob/master/CHANGELOG.md#version-035-3-october-2019

Here is the link of the latest release that comes with the SDWebImage version 5.x support and update to SDK v3.7.0: https://github.com/CleverTap/clevertap-react-native/releases/tag/0.3.5

Thanks!

**Comment by vogosamvelraja** [comment]
@Aditi3  Thanks for the quick response! Closing the same.
