### ISSUE TITLE
[Android] Expose clevertap instance for branch.io integration

### ISSUE THREAD

**Issue by ebellumat** [CleverTap/clevertap-react-native#57]
Following this guide of Branch.io, to integrate i need to implement this piece of code, but i don't have the Clevertap instance on React Native Clevertap MainApplication.java, how to solve this?

```java Branch branch = Branch.getInstance();
branch.setRequestMetadata("$clevertap_attribution_id",
cleverTapInstance.getCleverTapAttributionIdentifier()); 
```

The Branch.io guide:
https://docs.branch.io/integrations/clevertap/

**Comment by darshanclevertap** [comment]
@ebellumat We do have a JS method for this. You can use that to get the Attribution ID and pass it to Branch

**Comment by darshanclevertap** [comment]
@ebellumat Is your issue resolved?

**Comment by ebellumat** [comment]
Yes, but i had to disable the native implementation of these guys on iOS for preventing duplication...

**Comment by krishnaff** [comment]
Looks like this won't work in JS because the "$clevertap_attribution_id" is needed **before** the Branch.initSession(...) is called.

From Branch docs
```
Branch branch = Branch.getInstance();
branch.setRequestMetadata("$clevertap_attribution_id",
cleverTapInstance.getCleverTapAttributionIdentifier());
```
From CleverTap docs
```
Branch branch = Branch.getInstance();
branch.setRequestMetadata("$clevertap_attribution_id",
cleverTapInstance.getCleverTapAttributionIdentifier());
...
Branch.initSession(...);
```

If anyone did get this working, could you post a snippet or explain how you're achieving this please?
