### ISSUE TITLE
[Android] Expose getUnreadMessages(), getAllMessages() for custom AppInbox

### ISSUE THREAD

**Issue by uraniumreza** [CleverTap/clevertap-react-native#59]
We wanted to build our own AppInbox UI on react-native and by calling APIs from clevertap we'll manage showing, marking and deleting messages! Can you guys please help me with the flow?

**Comment by darshanclevertap** [comment]
@uraniumreza We do not have JS methods exposed for the same in our React Native SDK for now. We will take this request as a feature enhancement and keep you posted regarding the timelines. For now, if you're willing to write native Android/iOS code for the same you can refer our documentation here for [Android](https://developer.clevertap.com/docs/android#section-creating-your-own-app-inbox) and [iOS](https://developer.clevertap.com/docs/ios#section-step-3-creating-your-own-app-inbox-).

**Comment by uraniumreza** [comment]
For now, I'm using `react-native-clevertap-inbox` npm package for the purpose but it'd be great if you guys expose those methods in this package and a proper guideline! It'll be helpful for us as the source-of-truth will be this one for any upcoming breaking changes!

**Comment by ebellumat** [comment]
Thanks for the tip of the package, @uraniumreza

**Comment by ebellumat** [comment]
Any update, guys? This feature, native display and key-value pair from notifications and inApp are important features to keep us without.

**Comment by Aditi3** [comment]
Hi @ebellumat @uraniumreza 

Here is the link of the latest release that comes with Custom App Inbox and InApp Notification/ App Inbox kv button click listeners support
https://github.com/CleverTap/clevertap-react-native/releases/tag/0.4.0

Thanks for your patience.
