### ISSUE TITLE
'CleverTap.h' file not found

### ISSUE THREAD

**Issue by cursivedgreat** [CleverTap/clevertap-react-native#64]
React Native version 0.59

#import "CleverTapReactManager.h"
#import "CleverTapReact.h"

#import <UIKit/UIKit.h>

#import <React/RCTLog.h>

#import "CleverTap.h"
#import "CleverTap+Inbox.h"
#import "CleverTap+ABTesting.h"
#import "CleverTapEventDetail.h"
#import "CleverTapUTMDetail.h"
#import "CleverTapSyncDelegate.h"
#import "CleverTapInAppNotificationDelegate.h"

@interface CleverTapReactManager() <CleverTapSyncDelegate, CleverTapInAppNotificationDelegate> {
}

@end

Podfie entry is 
  pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native'

package.json entry is 
"clevertap-react-native": "^0.3.6"
platform iOS

**Comment by Aditi3** [comment]
Hi @cursivedgreat 

If you are on RN version 0.59, I recommend you to install the previous version of the SDK that is below v0.3.6.

We did changes in the header format in our current v0.3.6 to support the latest versions of the RN 0.60.x.

**Comment by Aditi3** [comment]
Closing it, feel free to reopen if you need further help or you can also write to support@clevertap.com.

**Comment by Skullflow** [comment]
Hi, I'm using version 0.3.5 and I still have this error ('CleverTap.h' file not found).

I'm using react native v 0.59.10, I linked the project manually and I added `pod 'CleverTap-iOS-SDK'`.

Last, i tried with AND without `use_framework!`

Any tips to resolve this?

**Comment by JamesDullaghan** [comment]
Running into this same issue. Any input would be appreciated.

**Comment by Skullflow** [comment]
Hi,

you have to use modular headers in your podfile (and remove `use_framework!`, like this:
`pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native', :modular_headers => true`.

Make sure that `clevertap-react-native` is unlinked from the project.
