### ISSUE TITLE
[React-Native]'CleverTapReact/CleverTapReactManager.h' file not found

### ISSUE THREAD

**Issue by JhonJimenezCastro** [CleverTap/clevertap-react-native#69]
According to "Note: Need to use @import CleverTaSK; instead of #import <CleverTapSDK / CleverTap.h> in the AppDelegate class in case if using use_modular_headers! in the podfile."
[https://github.com/CleverTap/clevertap-react-native/blob/master/docs/integration.md](url)

when using @import CleverTaSK; no option is provided to replace #import <CleverTapReact / CleverTapReactManager.h>.

Can this be omitted? or what is the correct way to import <CleverTapReact / CleverTapReactManager.h>. when using use_modular_headers!

![image](https://user-images.githubusercontent.com/50895087/73560959-09acff80-4426-11ea-946d-ff14130d353a.png)

### My podfile

platform :ios, '10.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

target 'MyTargetName' do
  use_modular_headers!
  pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native'
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec',:modular_headers => false
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  use_native_modules!
  use_unimodules!
  
end

**Comment by Aditi3** [comment]
Hi @JhonJimenezCastro 

You can `@import CleverTapReact;` instead of ` import <CleverTapReact / CleverTapReactManager.h>` in your AppDelegate class.

We will include this in our documentation as well.

Thanks!

**Comment by JhonJimenezCastro** [comment]
> Hi @JhonJimenezCastro
> 
> You can `@import CleverTapReact;` instead of ` import <CleverTapReact / CleverTapReactManager.h>` in your AppDelegate class.
> 
> We will include this in our documentation as well.
> 
> Thanks!

This worked for me, thank you very much.
