### ISSUE TITLE
clevertap Android sdk version update

### ISSUE THREAD

**Issue by ajmeersha** [CleverTap/clevertap-react-native#70]
u r still using sdk version 3.6.0 , but some of the clevertap features only works on sdk version greater than 3.6.1+ , when we ll get the new sdk support for react native?

**Comment by ebellumat** [comment]
I Need Native display, support.

**Comment by darshanclevertap** [comment]
@ajmeersha @ebellumat Guys, we are working very hard on this. Our team has limited bandwidth on this right now but rest assured we will try to get this out ASAP. I will come back to you with concrete timelines early next week.

**Comment by ebellumat** [comment]
@darshanclevertap Hire me! I sure i can improve the bandwidth, guys! I will really enjoy if i can be part of the team! 😃

**Comment by darshanclevertap** [comment]
Closing this as we've updated to the latest versions on both Android and iOS.
