### ISSUE TITLE
How to Unregister for Push?

### ISSUE THREAD

**Issue by leekuo** [CleverTap/clevertap-react-native#72]
We're currently using this call to register for push notifications from Clevertap:
    CleverTap.registerForPush()

But in the use case where the user logs out of our application, we see they are still getting push notifications.  How can we unregister them from Clevertap push notifications?  I don't see anything in the docs or the React Native wrapper functions here https://github.com/CleverTap/clevertap-react-native/blob/master/index.js

Thanks,
Lee

**Comment by Aditi3** [comment]
Hi @leekuo 

To disable push notifications for a user, set **MSG-push** to false as user property and push the user profile. 
Helping documentation: https://developer.clevertap.com/docs/concepts-user-profiles#section-overview

Thank you.

**Comment by leekuo** [comment]
Thank you @Aditi3 will give that a try!

**Comment by Aditi3** [comment]
Hi @leekuo 

I am going to close this issue here. If you need further help please feel free to email support at support@clevertap.com.

Thank you.

**Comment by bharatbrovitech** [comment]
@Aditi3 - https://github.com/CleverTap/clevertap-react-native/issues/23#issuecomment-1141958084
