### ISSUE TITLE
[iOS, Android] Native display support?

### ISSUE THREAD

**Issue by ebellumat** [CleverTap/clevertap-react-native#73]
When this feature will be added to this bridge?

https://docs.clevertap.com/docs/native-display

**Comment by ebellumat** [comment]
Any update?

**Comment by Aditi3** [comment]
Hi @ebellumat

**Comment by Aditi3** [comment]
Hi @ebellumat 

Apologies for the delay in getting back here. 
You can expect the Native Display support in our React-native SDK by mid-March.

Thank you.

**Comment by ebellumat** [comment]
Thank you! I'm really excited to use this feature.

**Comment by akshay-gupta-93** [comment]
Hey do we have any update on Native Display. When exactly are you guys planning to add it.

**Comment by Aditi3** [comment]
Hi @akshay-gupta-93 

We have already added support for Native Display in our development branch and currently, it's in the QA.

The release will be available in a day or two. We will keep you posted.

**Comment by akshay-gupta-93** [comment]
Thanks for the quick response. Waiting eagerly for the feature.

**Comment by Aditi3** [comment]
Hi @ebellumat @akshay-gupta-93 

Here is the link of the latest release that comes with Native Display Support
https://github.com/CleverTap/clevertap-react-native/releases/tag/0.4.0

Thanks for your patience.

**Comment by akshay-gupta-93** [comment]
Thanks @Aditi3 . I will start using it soon.

**Comment by akshay-gupta-93** [comment]
Hi @Aditi3 , Do you have any documentation on, how to use it?

**Comment by Aditi3** [comment]
Hi @akshay-gupta-93 

A few helping Links:

Check out our Starter Project [here](https://github.com/CleverTap/clevertap-react-native/blob/master/Starter/App.js) to understand the implementation of Native Display.
[See the CleverTap JS Interface:](https://github.com/CleverTap/clevertap-react-native/blob/master/index.js) for getting details regarding all available methods.
Native Display User Documentation Link: https://docs.clevertap.com/docs/native-display

**Comment by akshay-gupta-93** [comment]
@Aditi3  thanks, I will check.

**Comment by akshay-gupta-93** [comment]
@Aditi3 Now I am able to fetch native display data.I have two native display channels, and i am using 

CleverTap.getAllDisplayUnits((err, res) => {
             console.log('All Display Units: ', res, err);
});

to fetch the native display unit.

This is only returning me one of the native displays. I was hoping to get both of them. Can you please check?

Also, I am not sure how to create events to know which of the carousel item was clicked, viewed.
Can you please help me with that too. I have tried finding it out in the documentation. I don't see anything related to it.

**Comment by Aditi3** [comment]
Hi @akshay-gupta-93 

We will be needing more details in order to assist you with the query regarding why you receiving only one Native Display at your end because the same seems to be working for us. Therefore, I request to you write to our support at support@clevertap.com. Definitely,  someone from support will help you.

Coming to tracking the Clicked and Viewed, CleverTap provides following methods to record Clicked and Viewed for Native Display

 ` pushDisplayUnitViewedEventForID:` https://github.com/CleverTap/clevertap-react-native/blob/master/index.js#L570

`pushDisplayUnitClickedEventForID:` https://github.com/CleverTap/clevertap-react-native/blob/master/index.js#L578

Hope this helps

**Comment by Aditi3** [comment]
Closing this, if you need further help you can also write to support@clevertap.com.

Thank you!

**Comment by akshay-gupta-93** [comment]
Thanks.
