### ISSUE TITLE
How to integrate push notification in react native android

### ISSUE THREAD

**Issue by vaibhavgavade** [CleverTap/clevertap-react-native#74]
I wanted information about which code should be add in   android folder

**Comment by darshanclevertap** [comment]
@vaibhavgavade 
For push notifications please follow the Android documentation - https://developer.clevertap.com/docs/android#section-push-notifications
Thanks

**Comment by Aditi3** [comment]
Hi @vaibhavgavade 

I am going to close this issue here. If you need further help please feel free to email support at support@clevertap.com.

Thank you.
