### ISSUE TITLE
[iOS] Push notification - APNSDeviceTokenNotForTopic (1)

### ISSUE THREAD

**Issue by ebellumat** [CleverTap/clevertap-react-native#77]
When i try to send a test notification, i get this message, how to solve this?

![image](https://user-images.githubusercontent.com/26942680/76362130-3a266a00-62ff-11ea-93df-54e3f2dea909.png)

**Comment by Aditi3** [comment]
Hi @ebellumat 

Apple Push Notification service (APNs) returns this when the device token doesn't match the specified topic. 

In the context of CleverTap and to resolve the above error ensure that the App bundle ID of the provisioning profile with which the application is deployed and sending the device token to CleverTap dashboard is matching the App bundle ID for which the CleverTap p12 certificate/ authentication token is configured.

Hope this helps.

**Comment by ebellumat** [comment]
Thanks!

**Comment by CHANDRAMOHANnegi** [comment]
I am able to get notification with clevertap test credentials when my ios phone is connected to xcode

but , I am getting this error While sending with prod credentials . i installed ipa in my ios device

@Aditi3
