### ISSUE TITLE
[iOS, Android] How to handle Custom key-value pair on Push Notification and InApp?

### ISSUE THREAD

**Issue by ebellumat** [CleverTap/clevertap-react-native#78]
In the dashboard, there is an option to send a key-value pair on push notification and inApp messages, how to get value back on this bridge? With Clevertap.getInitialUrl we only can get deep links.

![image](https://user-images.githubusercontent.com/26942680/76460778-70c2ba00-63bd-11ea-8e6d-f8b3b46de979.png)

**Comment by ebellumat** [comment]
Any update?

**Comment by Aditi3** [comment]
Hi @ebellumat 

CleverTap provides `CleverTapInAppNotificationDismissed` and `CleverTapInAppNotificationButtonTapped` listener which return the extra custom key/value pairs set in CleverTap dashboard for the In-App notification.

Our [Starter Project](https://github.com/CleverTap/clevertap-react-native/blob/master/Starter/App.js) explains how to implement the aforementioned listeners into an Application.

Hope this helps.

**Comment by agarwalnitesh** [comment]
Hi @Aditi3 

I'm sending Custom Key Pair value without using In-App notification, And unable to get back the key pair value when notification tap/open even after using CleverTapInAppNotificationDismissed and CleverTapInAppNotificationButtonTapped listener.

Please help.

**Comment by Aditi3** [comment]
Hi @agarwalnitesh 

Could you tell me which medium(Push notification or In-App Notification) you're using to send key/value pairs?

**Comment by agarwalnitesh** [comment]
Hi @Aditi3 

I am using Push notification

**Comment by Aditi3** [comment]
@agarwalnitesh 

Seems like you want to handle the push notifications payload and process the user's response to a notification.

Seems similar to #31

**Comment by Aditi3** [comment]
Closing it, if you need further help you can also write to support@clevertap.com.
