### ISSUE TITLE
clevertap SDK needs to be declared as an `api`. 

### ISSUE THREAD

**Issue by LonelyCpp** [CleverTap/clevertap-react-native#82]
In the dependency 
`implementation 'com.clevertap.android:clevertap-android-sdk:3.7.0'`

`implementation` hides the sdk from the project scope breaking the autolink react native feature. We need to manually update the sdk everytime now.

The deprecated `compile` is equivalent to `api`

**Comment by darshanclevertap** [comment]
@LonelyCpp Thank you for bringing this to our notice. Could you explain how does `implementation` scope breaks the auto-link feature?

Meanwhile, I will also take a look at this as well on my end as well.

**Comment by LonelyCpp** [comment]
If you see the `0.3.6` release, the [build.gradle](https://github.com/CleverTap/clevertap-react-native/blob/0.3.6/android/build.gradle), it has the sdk dependency specified as 
`compile 'com.clevertap.android:clevertap-android-sdk:3.6.0'`

This results in the sdk being exposed to the consumers of the library (react native apps). Thus the consumer need not explicitly declare in the its app's app level `build.gradle` file. 

Now since `compile` is deprecated, in favour of `api` and `implementation`, choosing `implementation`  here will result in the sdk no longer being exposed to consumers.

By using **`api`** instead would mean that the consumer app will use the sdk that comes with this library and will be updated along with any future version updates you guys may push out. (auto link unfriendly)

Stackoverflow [link](https://stackoverflow.com/questions/44493378/whats-the-difference-between-implementation-and-compile-in-gradle)
> Dependencies appearing in the api configurations will be transitively exposed to consumers of the library, and as such will appear on the compile classpath of consumers.

A similar example would be to look at [react-native-sentry](https://github.com/getsentry/sentry-react-native/blob/master/android/build.gradle). They specify the sentry sdk as an `api` dependency.

**Comment by darshanclevertap** [comment]
This has been fixed in v0.4.1. Closing this.

**Comment by LonelyCpp** [comment]
Thanks :)
