### ISSUE TITLE
Unable to handle the push notification payload and process notification onclick in Android

### ISSUE THREAD

**Issue by Poojapandey89** [CleverTap/clevertap-react-native#88]
Hi,
I want to process the received notification payload to handle onClick routing. Referring  the solution in #31 , I tried with custom handling using custom service as given in documentation and https://stackoverflow.com/questions/55350391/cannot-read-payload-of-push-notification-sent-from-clevertap-dashboard/55361276#55361276 
I am receiving the notifications but I am not able to find any method or way to handle onclick notification.

Thanks.

**Comment by Poojapandey89** [comment]
Can I please get a response on this as it is important feature and needs to be done asap.

**Comment by darshanclevertap** [comment]
@Poojapandey89 Sorry for the delay in replying. Are you passing the payload to the `createNotification` method as mentioned in the 2nd StackOverflow answer or are you rendering the Push Notifications on your own?

**Comment by Poojapandey89** [comment]
Yes @darshanclevertap , following the StackOverflow answer I am passing the payload to createNotification.
I want to handle the screen redirection on notification click, on the basis of notification i.e deeplinking. For that, is there any method to handle this?

**Comment by parthdani** [comment]
Hi @Poojapandey89, For Deep linking in React-native, you will have to create a schema in your Android Manifest file under Main Activity tag. So when you send a Push Notification from CleverTap and if you have mentioned this schema, we will open the Application and give the schema to your Android Manifest file which in turn will take it forward and will give the control to React-Navigation Plugin. For reference, attaching an example project over here: https://github.com/parthdani/CleverTapReactNativeDeeplinkExample

**Comment by darshanclevertap** [comment]
@Poojapandey89 Did this help with your issue?

**Comment by Poojapandey89** [comment]
yes @darshanclevertap, the solution helped me. Thank you so much @parthdani.
