### ISSUE TITLE
App is getting failed in compilation (Task :clevertap-react-native:mergeDebugShaders FAILED)

### ISSUE THREAD

**Issue by developerashish01** [CleverTap/clevertap-react-native#89]
* What went wrong:
Execution failed for task ':clevertap-react-native:mergeDebugShaders'.
> Failed to create directory '\node_modules\clevertap-react-native\android\build\intermediates\incremental\mergeDebugShaders'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by darshanclevertap** [comment]
@developerashish01 When is this happening? Can you print detailed stack trace of the issue?

**Comment by darshanclevertap** [comment]
@developerashish01 Also which version of the clevertap-react-native library are you using?

**Comment by darshanclevertap** [comment]
@developerashish01 We're closing this. If you're still facing this issue, feel free to reopen this thread.
