### ISSUE TITLE
App Inbox Style

### ISSUE THREAD

**Issue by kritikaiyeer** [CleverTap/clevertap-react-native#90]
I have seen the docs and the starter example here but styling key is not available for App Inbox Content when no messages are there ie. "No Message(s) received" text how can I style the color of this text it is default white I want to change it to black

**Comment by darshanclevertap** [comment]
@kritikaiyeer We do not have this as of now. Honestly, we never thought someone would want to customize that text :smile: 
We'll see if we can add this to our future releases.
