### ISSUE TITLE
App Inbox Deep Link

### ISSUE THREAD

**Issue by kritikaiyeer** [CleverTap/clevertap-react-native#91]
can we deep link app inbox to our push notification cta.

 ie. if the user clicks on the notification the app inbox should be opened.

**Comment by darshanclevertap** [comment]
@kritikaiyeer No it is not possible to have a deep link to the App Inbox. Configuring deep links is a prerogative of the app and the CleverTap SDK cannot define a deep link on the app's behalf. You could design your own App Inbox using our public APIs for App Inbox and create a deep link to it.
