### ISSUE TITLE
xiaomi push notification

### ISSUE THREAD

**Issue by vinny3273** [CleverTap/clevertap-react-native#92]
i didn't find xiaomi push notification documentation for react native . 
right now im following https://developer.clevertap.com/docs/xiaomi-push-notifications#section-pass-token-to-clever-tap this guide but it seems insufficient . i'm getting error Log.e(TAG,"CleverTap is NULL");

there is no where written how to do this https://developer.clevertap.com/docs/xiaomi-push-notifications#section-implement-a-broadcast-receiver-class 
or where to paste java snippet below this ?
i'm using react native version : 0.60.6
clevertap react native  : 0.4.2

**Comment by darshanclevertap** [comment]
@vinny3273 You'll have to integrate Xiaomi Push via native Android way only. We do have a JS method to pass the token to CleverTap, you can check that [here.](https://github.com/CleverTap/clevertap-react-native/blob/master/index.js#L95)
Also, someone from my support team has shared the Broadcast Receiver sample code. Please do check that and let us know if it worked for you.

**Comment by vinny3273** [comment]
@darshanclevertap 
thank you for quick response .
1- is it mandatory to pass token from JS method ? through setPushToken ? 
its automatically getting captured for me right now .

2 - 
i have done this part in MainActivity.java

` CleverTapAPI cleverTapAPI;

   MiPushClient.registerPush(this, "string", "string");
        String xiaomiToken = MiPushClient.getRegId(this);
        if(cleverTapAPI != null){
            cleverTapAPI.pushXiaomiRegistrationId(xiaomiToken,true);
        }else{
            Log.e("clevertap","CleverTap is NULL");
        }`

but i'm always getting clevertap CleverTap is NULL . its going in else case
what could be wrong ?

3 - shared where , sorry ? i didn't receive any mail .

**Comment by darshanclevertap** [comment]
@vinny3273 Passing the token via JS is not mandatory.

You need to initialize the `cleverTapAPI` object in that piece of code.

Add the following line of code just before the `if` statement -

`cleverTapAPI = CleverTapAPI.getDefaultInstance(MainActivity.this)`

then the above piece of code should work for you.

**Comment by darshanclevertap** [comment]
I think you have written to support@clevertap.com, so my support team said they have replied to you as well.

**Comment by vinny3273** [comment]
yes, i'm having  conversation with jay . thank you

after getting broadcast file , app is running , with debug level 2 i'm not seeing any error with app or clevertap. i'm using oneplus 7t
but when i search xiaomi related logs i get this

2020-05-01 21:23:58.659 23694-23826/com.abc.app E/ManifestChecker: com.xiaomi.mipush.sdk.x$a: Receiver: none of the subclasses of PushMessageReceiver is enabled or defined.
        at com.xiaomi.mipush.sdk.x.c(Unknown Source:210)
        at com.xiaomi.mipush.sdk.x.b(Unknown Source:0)
        at com.xiaomi.mipush.sdk.y.run(Unknown Source:20)
        at java.lang.Thread.run(Thread.java:919)



2020-05-01 21:23:58.784 23694-23822/com.gamingmonk.app V/xiaomi: [Thread:20666] loadClass fail hasContext= false, errMsg = miui.os.Build
2020-05-01 21:23:58.796 23694-23822/com.gamingmonk.app V/xiaomi: [Thread:20666] Don't send message before initialization succeeded!
2020-05-01 21:23:58.802 23694-23822/com.gamingmonk.app V/xiaomi: [Thread:20666] Don't send message before initialization succeeded!

**Comment by darshanclevertap** [comment]
@vinny3273 I think you need to check Proguard rules for Xiaomi Push SDK. I think Xiaomi classes are getting obfuscated and it cannot find the classes inherited from PushMessageReceiver

**Comment by darshanclevertap** [comment]
@vinny3273 Also check if the Broadcast Receiver you have coded is declared in the AndroidManifest.xml file

**Comment by vinny3273** [comment]
yes broadcast receiver was missing from android manifest . 
thank you for the help , closing the issue now.
