### ISSUE TITLE
Unstable response on Android (getAllInboxMessages)

### ISSUE THREAD

**Issue by gaelperon** [CleverTap/clevertap-react-native#95]
Hello Clevertap,

We are using your react native SDK in our app.

The setup part is OK and everything is working fine on iOS, but we are facing some issues retrieving Inbox messages on Android devices.

We are facing multiple cases :
* On one android emulator (Nexus 5X, API 29) CleverTap.getAllInboxMessages returns a random value (sometimes an empty array, sometimes the expected array of inbox messages).
* On another emulator (3.2 QVGA_ADP2 API29) CleverTap.getAllInboxMessages always returns an empty array (for the exact same identity used in the previous emulator)

Everything seems to be ok on the back office side (online dashboard) because we can find the user by its identity and see all the events.

When we analyze the network traffic of the Android profiler, nothing seems to be happening when calling  CleverTap.getAllInboxMessages

Could you tell us on which calls are the new messages fetched? 
Userlogin ? Fetch ? GetInboxMessages ?

Setup info : 

React native SDK Version
`"clevertap-react-native": "^0.4.3"
`
Android SDK Version
`implementation 'com.clevertap.android:clevertap-android-sdk:3.8.0'`

**Comment by darshanclevertap** [comment]
@gaelperon So the Inbox Messages are stored in the SDK database. Hence, you will not notice any network call when you call `getAllInboxMessages`. New messages are fetched when the App is launched and stored in the database. Once they're stored we give a callback to React Native using `CleverTapInboxMessagesDidUpdate`. You can find the [example usage here](https://github.com/CleverTap/clevertap-react-native/blob/master/Starter/App.js)

I believe the emulator could be a reason for different responses. I'd suggest using a proper Android device for testing

**Comment by gaelperon** [comment]
@darshanclevertap thanks! It solves my problem

Maybe you should add this explanation about callbacks in the documentation because it clarifies a lot how it works

**Comment by darshanclevertap** [comment]
@gaelperon Thank you for this feedback, we will definitely take this and improve our documentation. Closing this thread as your issue has been resolved.

**Comment by gaelperon** [comment]
Just one more question: what's the purpose of initializeInbox? And what happens if you don't initialize the inbox?

**Comment by darshanclevertap** [comment]
@gaelperon `initializeInbox` initializes the entire App Inbox mechanism in the CleverTap SDK. None of the inbox methods will give you a result if you don't call `initializeInbox`

Also `initializeInbox` has its own callback `CleverTapInboxDidInitialize` in React Native. Once the Inbox is initialized, you should call the inbox related functions. 

I'm sorry there is no detailed React Native documentation around this but if you're familiar with Android you can read [this section here](CleverTapInboxDidInitialize) of our Android documentation

**Comment by gaelperon** [comment]
@darshanclevertap thanks, we were supposing that it was this behavior, but now we have confirmation.
