### ISSUE TITLE
Getting error using RemoveListener on iOs

### ISSUE THREAD

**Issue by gaelperon** [CleverTap/clevertap-react-native#98]
Hi,
        
When I use the function `CleverTap.removeListeners() `, I have an error on iOS. 
Everything is working fine on Android.

You can see the error attached
![Simulator Screen Shot - iPhone 11 - 2020-06-12 at 16 18 04](https://user-images.githubusercontent.com/5892710/84516853-acc42e80-acce-11ea-8af2-606f8077591a.png)

And here is my snippet of code :

 ```
 useEffect(() => {
    CleverTap.addListener(
      CleverTap.CleverTapProfileDidInitialize,
      (event: any) => {
        setIsClevertapLoggedIN(true);
      },
    );

      return () => {
        CleverTap.removeListeners();
      };
    
  }, []);
```

**Comment by gaelperon** [comment]
Hi @Aditi3, any idea on that issue?

**Comment by Aditi3** [comment]
Hi @gaelperon 

It seems an unexpected behavior. We're executing the same code in both Android and iOS which is removing all listeners.  

```
 removeListeners: function() {
        if (EventEmitter) {
            EventEmitter.removeAllListeners();
        }
  }
```
Please allow me some time to check the same at my end and I will get back to you with an update shortly. 

Currently, if this is a blocker for you, I would recommend removing listeners at your end by calling **removeAllListener()**

Thank you!

**Comment by gaelperon** [comment]
Hi @Aditi3 

I see you added a fix. 
Will this be included in the next release?

**Comment by Aditi3** [comment]
Hey @gaelperon 

Yes, the change will be included in the next release. We're verifying the change for the Android platform and compatibility with the different versions of the React-Native.
