### ISSUE TITLE
jest test issue 

### ISSUE THREAD

**Issue by AbdullhRtima** [CleverTap/clevertap-react-native#99]
Hi, I face an issue with "clevertap-react-native" with jest test,
I ignore the `clevertap-react-native` but no luck still get this error :(
```
$ jest --detectOpenHandles
 FAIL  __tests__/App-test.tsx
  ● Test suite failed to run

    TypeError: Cannot read property 'CleverTapProfileDidInitialize' of undefined

       9 |  *********************************************************************************************************************/
      10 | 
    > 11 | import CleverTap from "clevertap-react-native";
         | ^
      12 | import { Linking } from "react-native";
      13 | import { SupportedEvents } from "./supported-events";
      14 | 

      at Object.<anonymous> (node_modules/clevertap-react-native/index.js:38:51)
      at Object.<anonymous> (src/utils/clever-tap/clever-tap.ts:11:1)

```

**Comment by piyush-kukadiya** [comment]
Hi @AbdullhRtima,
Can you please provide steps to reproduce this issue?

**Comment by darshanclevertap** [comment]
@AbdullhRtima Are you still facing this issue? If yes, can you please provide us the steps to reproduce and the version of ReactNative you're using?

**Comment by kumaratulismu** [comment]
@AbdullhRtima Can you please confirm on the issue?

**Comment by kumaratulismu** [comment]
@AbdullhRtima I have tried to create a sample [application](https://github.com/kumaratulismu/SampleReactNativeApp) with jest test case.

It’s working for me. 

If you still face the issue please help us by forking & modifying the above app to replicate the same.

Thanks
Atul

**Comment by DeniferSantiago** [comment]
> @AbdullhRtima I have tried to create a sample [application](https://github.com/kumaratulismu/SampleReactNativeApp) with jest test case.
> 
> It’s working for me.
> 
> If you still face the issue please help us by forking & modifying the above app to replicate the same.
> 
> Thanks
> Atul

Link returns 404 error

**Comment by ahsanTradeling** [comment]
same issue , any solution?

**Comment by mathioni-tc** [comment]
To fix this issue for me, i just create a file: `__mocks__/clevertap-react-native.ts`
```javascript
export default {
  CleverTapProfileDidInitialize: jest.fn(),
};
```
